(function(z){
'use strict';var v7=function(a){z.L.call(this);this.aa(a)},w7=function(a){z.L.call(this);this.aa(a)},w6a=function(a,b){this.user=a;this.quotes=b},x6a=function(a,b){b=b.g();if(b===Number||b.$isProtoEnum)return a=Number(a),Number.isNaN(a)?void 0:a;if(b===Boolean)return!!a;if(b===String)return String(a)},x7=function(a){return a.$B.best||null},y7=function(a,b){b=b.filter(function(a){return"anon"!=a.mb()});b=z.bb(b,function(a){return a.mb()},a);return z.fb(b).map(function(a){return new w6a(a[0].hc(),a)},
a)},y6a=function(a,b,c,d){return(0,z.Kc)(a.cu[b.name]||[],function(a){return a.Fd()==c&&a.Ce()==d})},z7=function(){this.HH=1},A7=function(a){z.uh.call(this);this.aa(a)},z6a=function(a,b){return z.K(a,"slots",b)},A6a=function(a,b){return z.K(a,"requestContext",b)},B7=function(a){z.L.call(this);this.aa(a)},C7=function(a){return z.J(a,"inResponseToMediaResource")},D7=function(a){return z.J(a,"mediumQuote")},B6a=function(a,b){a.YQ=b;return a},E7=function(a,b){return x7(a)?z.OC(x7(a)).filter(function(a){return this.f6(a)==
b},a):[]},C6a=function(a){a=new Date(a);return Date.UTC(a.getFullYear(),a.getMonth()+1,1)-1},D6a=function(a){var b=z.MM(a.lk.Dt,a.lk.Xr(),a.um.Dt,a.um.Xr()).Ia().trim();0<a.lk.Xr()&&(b="…"+b);var c=z.zD(a.Cc,a.um.Dt);a.um.Xr()<c.Ia().length&&(b+="…");return b},E6a=function(a){var b=z.sB(a.nAa),c=a.lk.Dt,d=c?b.indexOf(c):-1,e=(c=a.um.Dt)?b.indexOf(c):-1;if(-1==d||-1==e)return"";for(c=[];d<=e;d++)c.push(z.zD(a.Cc,b[d]));b=z.Ma(c);a=z.vt(c.indexOf(c[0]),a.lk.Xr(),c.indexOf(b),a.um.Xr(),!1);return z.nka(new z.it(z.Gl,
z.jEa),c,a,!0)},F6a=function(a,b,c){c=c.yy;b=b.getAttribute("name").split(" ");var d=z.qb(b);a=(a.cu[c.name]||[]).filter(function(a){return d[a.fj()]});return a.length?z.gwa(a):null},G6a=function(a,b,c,d){b=y6a(a,b,c,d);return y7(a,b)},H6a=function(a,b){var c=0;(a.cu[b]||[]).forEach(function(a){"anon"==a.mb()&&(c+=a.Me())});return c},I6a=function(a,b,c){var d=a.na.la(z.SDa,{postId:b},{filter:c});return z.lD(a,d,function(){return this.Cb.Rl(d)})},J6a=function(a,b){return z.sa(b)in a.KA},K6a=function(a,
b){z.Rs(a,7);var c=new z.Is("",1,a.Ia());b.forEach(function(a){z.Ps(c,z.zs(a.startOffset,a.endOffset,[a.quoteId],[a.userId]))},a);b=z.aka(c);for(var d=z.bka(c,b),e=0;e<b.length;e++){var g=d[e];if(g.length){for(var k={},l=[],p=0;p<g.length;p++){var r=g[p];k[z.J(r,"creatorIds")]=!0;l.push(r.getName())}g=b[e];p=e<b.length-1?b[e+1]:a.Ia().length;z.Ps(a,z.zs(g,p,l,Object.keys(k)))}}},L6a=function(a,b){var c=a.text,d=a.l,e="";a=""+z.A(z.Ch(a));a=(0,z.N)(a);e+=z.A(z.O({s:c,ac:!0,Ye:!0,href:(0,z.M)(""+z.H(b.rq)),
source:a,style:"link.obvious",wa:!0,l:d},b));return(0,z.y)(e)},M6a=function(a,b,c){b="";a.$Ha?a=z.n("Top highlight"):(c=""+z.A(z.eP(z.D({m7:!0,Cma:!c.useragent.isMobile},a),c)),1==a.Ki&&a.isActive&&(a=z.n("highlighted"),c+=" "+a),a=(0,z.y)(c));b+=a;return(0,z.y)(b)},F7=function(a,b){this.si=a;this.Zta=b;this.Re=(this.Uk=b=z.nB(a.node,b))&&b.getAttribute("name");this.LQ=b?z.mw(a,b):-1},G7=function(a){var b=a.length;a=a.match(N6a);if(!a)return b;for(var c=0;c<a.length;c++)b+=23-a[c].length;return b},
O6a=function(a,b,c){return(0,z.y)(z.PO(z.D({user:c.currentUser,type:"quoteResponses"},a),c))},P6a=function(a,b,c){return(0,z.y)(z.A(z.wj({icon:(0,z.N)(""+z.A(z.$i())),wa:!0,action:"dismiss-meter",l:"js-dismissMeterButton"},c)))},Q6a=function(a){var b,c="";switch(z.qa(b=a.meteringInfo.postIds.length)?b.toString():b){case 0:case 1:a=z.n("Your first three are on the house.");c+=a;break;case 2:a=z.n("That’s two for you...");c+=a;break;default:a=z.n("We like your style."),c+=a}return(0,z.y)(c)},H7=function(a){z.L.call(this);
this.aa(a)},R6a=function(a,b,c){b="\x3cdiv class\x3d'u-marginLeft10'\x3e\x3cdiv class\x3d\"buttonSet u-inlineBlock\"\x3e"+z.A(z.wj({action:"quote",source:"quote_popover",icon:(0,z.N)(""+z.A(z.eea())),l:(0,z.N)("button--highlightMenu u-sm-height42 u-sm-lineHeight44 u-accentColor--highlightStrong js-quoteAttributions-pileOn"),ac:!0,Vj:!0,YS:"quote",wa:!0,isActive:a.isActive},c))+(c.supportsEdit?z.A(z.wj({action:"quote-respond",source:"quote_popover",icon:(0,z.N)(""+z.A(z.jea())),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",
ac:!0,wa:!0},c)):"")+(a.yW?z.A(z.wj({action:"twitter",source:"quote_popover",icon:(0,z.N)(""+z.A(z.ij(null))),l:"button--highlightMenu u-sm-height42 u-sm-lineHeight44",ac:!0,wa:!0},c)):"")+'\x3cdiv class\x3d"buttonSet-separator"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"'+z.F(z.E("js-quoteAttributions-info u-inlineBlock u-verticalAlignTop u-noWrapWithEllipsis u-maxWidth414 u-paddingTop11 u-paddingRight18 u-paddingBottom0 u-paddingLeft10 u-xs-paddingTop13 u-xs-paddingLeft4 u-xs-maxWidth160"))+
'"\x3e'+M6a(a,0,c)+"\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},I7=function(a){z.Il.call(this);var b=z.$m();this.lk=b&&new F7(z.Cn(b,!0),a);this.um=b&&new F7(z.Cn(b,!1),a)},J7=function(a,b){var c=new z.Dh(z.Fl(b)),c=new z.td(c.la(z.UCa)),d=new z.td("https://www.facebook.com/v2.7/dialog/share");z.Ad(d,z.Md({app_id:b.facebook.key,href:a.toString(),display:"popup",redirect_uri:c.toString()}));return d},S6a=function(a,b,c){function d(a){return a.replace(/“/g,"‘").replace(/”/g,"’").replace(/„/g,"‚").replace(/'/g,
"’")}b.content=d(b.content);b.name&&(b.name=d(b.name));var e=String(a(b,null,c)),g=G7(e)-280;0<g&&(b.content=z.bh(b.content,b.content.length-g),e=String(a(b,null,c)));return e},T6a=function(a,b){b=new z.Dh(b.authBaseUrl);return new z.td(b.Dl(a))},U6a=function(){var a=z.n("Highlights");return(0,z.y)(""+a)},V6a=function(a,b,c){b=a.post.virtuals.responsesCreatedCount>=c.j.H8&&(a.post.creator.userId==c.currentUser.userId||(null==a.post.homeCollection?null:null==a.post.homeCollection.virtuals?null:null==
a.post.homeCollection.virtuals.permissions?null:a.post.homeCollection.virtuals.permissions.canManageAll));var d=z.D({D9:b},a),d=d||{},d=d.D9;a=""+('\x3cdiv class\x3d"container u-maxWidth740"\x3e\x3cdiv class\x3d"responsesStreamWrapper u-maxWidth640 u-hide js-responsesStreamWrapper"\x3e'+(0,z.y)('\x3cdiv class\x3d"container responsesStream-title u-paddingTop15"\x3e\x3cdiv class\x3d"row"\x3e'+z.A(z.sO({title:(0,z.N)(""+z.A(z.jk())),LD:!0,Ug:(0,z.N)(""+(c.supportsEdit&&d?z.KNa(null,c):""))},c))+"\x3c/div\x3e\x3c/div\x3e")+
z.INa(z.D({te:b},a),c)+(b?z.JNa(a,c):"")+z.HNa(c)+"\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(a)},W6a=function(a,b,c){var d=a.l;b="";var e=c.useragent.isMobile&&!c.useragent.isTablet||1<(null==a.meteringInfo.postIds?null:a.meteringInfo.postIds.length),g;g=(0,z.N)(""+(e?"u-bottom15 u-sm-bottom10":"u-backgroundWhite u-boxShadowTop u-borderBottomLightest u-bottom0"));var k;k=(0,z.N)(""+(e?"u-backgroundWhite u-borderLightest u-boxShadow2px10pxBlackLighter u-borderRadius4":""));d='\x3cdiv class\x3d"postMeterBar u-sizeFullWidth u-fixed '+
z.F(g)+(d?" "+z.F(d):"")+' js-meterBanner" role\x3d"alert" aria-live\x3d"assertive"\x3e\x3cdiv class\x3d"u-borderBox u-maxWidth1040 u-marginAuto u-paddingTop25 u-paddingBottom25 u-paddingLeft20 u-paddingRight20 '+(e?z.F(k):"")+' u-sm-maxWidth740 u-xs-marginLeft10 u-xs-marginRight10 u-xs-paddingTop15 u-xs-paddingBottom15 u-xs-paddingLeft10 u-xs-paddingRight10"\x3e\x3cdiv class\x3d"u-flexCenter"\x3e\x3cdiv class\x3d"u-flex0 u-flexCenter"\x3e'+z.lF(a,c)+'\x3c/div\x3e\x3cdiv class\x3d"u-flex1 u-marginLeft20 u-marginTop8 u-xs-marginLeft10 u-xs-marginTop0"\x3e\x3cdiv class\x3d"'+
z.F(z.cl({sb:"regular"}))+' u-xs-hide"\x3e\x3cdiv class\x3d"ui-brand2"\x3e'+Q6a(a)+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"'+z.F(z.cl({sb:"small"}))+' u-xs-show"\x3e\x3cdiv class\x3d"ui-h4"\x3e'+Q6a(a)+'\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"u-flex0 u-marginLeft20 u-xs-marginLeft10 js-expandMeterButton"\x3e';g="";k=""+z.A(z.HO(null));k=(0,z.N)(k);if(c.useragent.isMobile)g+=z.A(z.wj({icon:k,wa:!0,action:"expand-meter"},c));else{var l=z.n("Details");g+=z.A(z.wj({text:(0,z.N)(""+l),
Sd:!0,icon:k,wa:!0,action:"expand-meter"},c))}g=(0,z.y)(g);var e=d+g+'\x3c/div\x3e\x3cdiv class\x3d"u-flex0 u-marginLeft40 u-flexCenter u-textColorNormal u-xs-marginLeft10 u-xs-hide js-dismissMeterIndicator"\x3e'+(e?(0,z.y)('\x3cfigure class\x3d"circleCountdown"\x3e\x3csvg role\x3d"img" xmlns\x3d"http://www.w3.org/2000/svg"\x3e\x3ccircle class\x3d"circleCountdown-fill" cx\x3d"50%" cy\x3d"50%" r\x3d"8px" /\x3e\x3c/svg\x3e\x3c/figure\x3e'):P6a(0,0,c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"postMeterBar-details u-marginLeft137 u-paddingLeft20 u-paddingRight20 '+
z.F(z.cl({sb:"regular"}))+' u-sm-marginLeft137 u-xs-margin0 u-xs-padding0 js-moreInfo"\x3e\x3cp class\x3d"ui-body u-marginVertical10 u-xs-paddingTop10 u-xs-borderTopLight"\x3e',p,d="";g=a.post.lockedPostSource==c.j.dA.bA;if(c.useragent.isMobile)if(g)switch(z.qa(p=a.meteringInfo.postIds.length)?p.toString():p){case 0:case 1:p=z.n("Enjoy daily, ad-free selections from The New York Times, The Atlantic, Fast Company, and more for $5/month.");d+=p;break;default:p=z.n("Access dozens of ad-free selections daily from the world’s leading publications for $5/month."),
d+=p}else switch(z.qa(p=a.meteringInfo.postIds.length)?p.toString():p){case 0:case 1:p=z.n("You can read three exclusive stories per month for free. Upgrade for unlimited access");d+=p;c.isAuthenticated||(p=z.n("sign in"),g=z.n(" or "),d+=g+L6a({text:(0,z.N)(""+p),susiEntry:c.j.Ha.Iaa},c));d+=".";break;case 2:p=z.n("You’ve read two of your three free exclusive stories this month.");d+=p;break;default:p=z.n("This is your last free exclusive story for this month. Upgrade for unlimited access."),d+=
p}else if(g)switch(z.qa(p=a.meteringInfo.postIds.length)?p.toString():p){case 0:case 1:p=z.n("Enjoy daily, ad-free selections from The New York Times, The Atlantic, Fast Company, and more, when you upgrade for $5/month.");d+=p;break;default:p=z.n("Unlock the best of {$productName} when you upgrade for $5/month. Access dozens of ad-free selections daily from the world’s leading publications.",{productName:z.A(c.productName)}),d+=p}else switch(z.qa(p=a.meteringInfo.postIds.length)?p.toString():p){case 0:case 1:p=
z.n("Members get exclusive access to the best stories on {$productName} — but you can read three for free each month. Upgrade for $5/month for unlimited access.",{productName:z.A(c.productName)});d+=p;c.isAuthenticated||(p=z.n("Already a member?"),d+='\x3cspan class\x3d"u-block u-marginTop20"\x3e'+p+" "+L6a({text:(0,z.N)("Sign in"),susiEntry:c.j.Ha.Iaa},c)+".\x3c/span\x3e");break;default:p=z.n("Unlock the best of {$productName} when you upgrade for $5/month. Access in-depth, insightful stories from top writers and publications.",
{productName:z.A(c.productName)}),d+=p}d=(0,z.y)(d);b+=e+d+'\x3c/p\x3e\x3cdiv class\x3d"u-marginTop20 u-xs-marginTop15"\x3e'+z.A(z.Uy({location:c.j.Id.Gaa,lb:!0,Ba:!0,zd:!0,ei:!0,postId:a.post.id,collectionId:a.post.homeCollectionId,authorId:a.post.creatorId,l:"u-xs-sizeFullWidth"},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e";return(0,z.y)(b)},K7=function(a,b,c){z.T.call(this);this.ze=a.get("quotes-data");var d=this.ze.tp;d.subscribe("add",this.Ffa,this);d.subscribe("remove",this.Ffa,this);
this.$a=b;this.we=b.pm;this.zm=c;this.eca=[];this.Ja=a.get("app");this.Ga=a.get("popover");this.na=a.get("route-builder");this.S_=a.get("global-event-bus");this.AAa=a.get("progressive-media-loader")},Y6a=function(a,b,c,d){var e=X6a(a,b);if(e){var g=a.$a.isPublished(),k=z.Awa(a.$a);e.yW=g&&k;if(c=z.WF(z.mC(z.lC(z.nC(z.RE(z.oC(a.Ga).kb(R6a,e),z.SE),c),{V6:!0,Jy:!0,Ba:!0}),"popover--quoteAttributions"),d).ua())c.em("deactivate",function(){this.Fp===b&&L7(this,null)},a),c.mo().fa("quote",a.Vua.bind(a,
c)).fa("quote-respond",a.Wua.bind(a,c)).fa("twitter",a.Xua.bind(a))}},X6a=function(a,b){if("anon"==b.mb())return{isActive:!1,$Ha:!0};var c=M7(a,b),d=b.Fd();b=b.Ce();a=G6a(a.ze,c,d,b);if(!a||!a.length)return null;a=(0,z.rb)(a,function(a){return a.user});c=(0,z.Kc)(a,function(a){return a.userId!=z.Rp().userId});return{isActive:(0,z.sc)(a,function(a){return a.userId==z.Rp().userId}),social:c,Ki:a.length}},Z6a=function(a,b){a=a.we.querySelectorAll('.markup--quote[name~\x3d"'+b.fj()+'"]');return z.Va(a)},
M7=function(a,b){b=b.gc()[0].name;return(b=z.ks(a.we,b))?a.$a.dj(b):null},$6a=function(a,b){var c=z.an(b);return(c=z.zE(a.zm,c))?F6a(a.ze,b,c):null},L7=function(a,b){a.Fp!==b&&(a.Fp&&a7a(a,a.Fp,!1),b&&a7a(a,b,!0),a.Fp=b)},a7a=function(a,b,c){Z6a(a,b).map(function(a){z.Oc(a,"is-targeted",c)})},N7=function(a,b){(b=b7a(a,b))&&z.xE(a.zk(),b)},b7a=function(a,b){var c=b.gc(),d=z.ks(a.we,c[0].getName());a=z.ks(a.we,z.Ma(c).getName());return z.MM(d,b.Fd(),a,b.Ce())},O7=function(a,b,c,d){a={postId:a.$a.Na(),
quoteId:b,source:d};z.kx(c?z.swa:z.uFa,a)},c7a=function(a){return(0,z.Kc)(z.sB(a),function(a){return 1==z.pB(a)})},d7a=function(a,b){z.rB(a,z.qB,z.Db(b,z.Cb(!0)),void 0)},e7a=function(a,b,c){z.na(a)||(a=a.toString());var d=window,e={scrollbars:!0,SKa:!0,toolbar:!1,location:!0,width:670,height:690};z.pb(e,c||{});e.left||e.top||(e.width=(0,window.parseInt)(e.width,10),e.height=(0,window.parseInt)(e.height,10),e.left=Math.max(d.screenX+Math.round(d.outerWidth/2-e.width/2),0),e.top=Math.max(d.screenY+
Math.round(d.outerHeight/2-e.height/2),0));var g={scrollbars:"scrollbars",SKa:"resizable",toolbar:"toolbar",location:"location",width:"width",height:"height",left:"left",top:"top"};c=z.oia(e,function(a,b,c){g[c]&&("boolean"==typeof b&&(b=b?"yes":"no"),a.push(g[c]+"\x3d"+b));return a},[]).join();return d.open(a,b,c)},f7a=function(a){var b=z.Nv(z.bya,{YIa:!0});b&&(b=b.split(/\s+/),b=b.filter(function(a){return!z.Aa(a)}),b.length&&z.Jc(a,b))},g7a=function(a){return(0,z.y)(z.A(z.ik(String(a.content)))+
" — "+z.A(z.Zr(a))+" "+z.A(a.url))},h7a=function(a,b,c){return(0,z.yh)("https://"+z.Fg(c.textshotHost)+"/image")},i7a=function(a,b,c){return(0,z.yh)("https://twitter.com/"+z.Fg(c.currentUser.twitterScreenName)+"/status/"+z.Fg(a.id))},j7a=function(){var a=z.y,b;b=z.n("Failed to load image");b=(0,z.y)(""+b);return a('\x3cspan class\x3d"tweetEditor-imageStatusIcon"\x3e\x26times;\x3c/span\x3e'+z.A(b))},k7a=function(a,b,c){b=z.y;a='\x3cdiv class\x3d"tweetEditor u-sizeFullWidth"\x3e\x3cdiv class\x3d"js-tweetEditor-error tweetEditor-error u-paddingBottom10 u-textAlignCenter u-textColorRed"\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-avatar"\x3e'+
z.A(z.Ck({user:a.user,Af:!0},c))+'\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-tweetContainer"\x3e\x3cdiv class\x3d"tweetEditor-textContainer"\x3e\x3cdiv class\x3d"js-tweetEditor-text textInput textInput--chromeless u-textAlignLeft"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"tweetEditor-textshot"\x3e\x3cdiv class\x3d"js-tweetEditor-imageStatus tweetEditor-imageStatus"\x3e';var d;d=z.n("Loading image attachment…");d=(0,z.y)(""+d);a=a+z.A(d)+"\x3c/div\x3e";d={};d=(0,z.y)(z.Ki(z.D({name:"addCircled",
size:"21px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"21" height\x3d"21" viewBox\x3d"0 0 21 21" \x3e\x3cpath d\x3d"M2.286 12.691a8.358 8.358 0 0 0 2.192 3.831A8.298 8.298 0 0 0 8.3 18.715c.73.19 1.462.288 2.192.29a8.363 8.363 0 0 0 2.2-.29 8.286 8.286 0 0 0 3.822-2.193 8.264 8.264 0 0 0 2.201-3.82c.19-.732.285-1.462.285-2.193a8.248 8.248 0 0 0-.285-2.2 8.265 8.265 0 0 0-2.2-3.823 8.258 8.258 0 0 0-3.822-2.2A8.66 8.66 0 0 0 10.5 2a8.188 8.188 0 0 0-2.192.286 8.33 8.33 0 0 0-3.831 2.2 8.298 8.298 0 0 0-2.193 3.822A8.66 8.66 0 0 0 2 10.5c0 .731.095 1.461.286 2.191zm1.557-.413a6.74 6.74 0 0 1-.239-1.773c0-.592.08-1.184.24-1.773a6.77 6.77 0 0 1 1.786-3.09 6.73 6.73 0 0 1 3.085-1.79c.59-.16 1.181-.24 1.777-.24.596 0 1.188.08 1.777.24a6.736 6.736 0 0 1 3.094 1.786 6.801 6.801 0 0 1 1.787 3.094c.16.59.239 1.178.239 1.768 0 .59-.08 1.182-.24 1.778a6.75 6.75 0 0 1-1.786 3.093 6.801 6.801 0 0 1-3.094 1.787 6.707 6.707 0 0 1-3.545 0A6.74 6.74 0 0 1 5.63 15.37a6.746 6.746 0 0 1-1.787-3.093zm2.937-2.055c0-.134.049-.25.148-.345a.494.494 0 0 1 .359-.143H9.23a.478.478 0 0 0 .35-.148.475.475 0 0 0 .147-.35V7.303c0-.141.048-.262.144-.363a.458.458 0 0 1 .345-.152h.562c.134 0 .25.05.35.152a.502.502 0 0 1 .147.363v1.934c0 .135.048.252.143.35a.46.46 0 0 0 .345.148h1.945c.14 0 .26.048.358.143.099.096.148.21.148.345v.562a.476.476 0 0 1-.148.35.486.486 0 0 1-.358.147h-1.945a.472.472 0 0 0-.345.143.47.47 0 0 0-.143.345v1.944c0 .14-.05.262-.148.36a.478.478 0 0 1-.35.147h-.56a.498.498 0 0 1-.489-.507V11.77a.461.461 0 0 0-.148-.345.487.487 0 0 0-.35-.143H7.287a.488.488 0 0 1-.36-.147.476.476 0 0 1-.147-.35v-.562z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
d)));d=(0,z.N)(""+z.A(d));var e;e=z.n("Include quote image");e=(0,z.y)(""+e);a=a+z.A(z.wj({icon:d,isPrimary:!0,wa:!0,l:"js-tweetEditor-addTextshot u-hide",action:"add-textshot",text:(0,z.N)(""+z.A(e))},c))+'\x3cdiv class\x3d"js-tweetEditor-imageContainer tweetEditor-imageContainer"\x3e';d=(0,z.N)("\x26times;");e=z.n("Remove quote image from tweet");e=(0,z.y)(""+e);return b(a+z.A(z.uj({s:d,Xc:!0,l:"js-tweetEditor-removeTextshot tweetEditor-removeTextshot",title:(0,z.N)(""+z.A(e)),action:"remove-textshot"},
c))+'\x3cimg class\x3d"js-tweetEditor-image tweetEditor-image" data-action\x3d"toggle-expand-image"\x3e\x3c/img\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'+(c.variants.textshots_userid?'\x3cdiv class\x3d"u-textColorRed"\x3eTweet to test account @fuzzyoctopusfee\x3c/div\x3e':""))},l7a=function(){var a=z.n("An error occurred, and the tweet wasn’t posted to Twitter.");return(0,z.y)(""+a)},m7a=function(a,b,c){var d="";b=z.n("Tweet posted.");a=a.eMa;var e;e=z.n("View the tweet");e=(0,z.y)(""+
e);d+=b+" "+z.A(z.O({xb:!0,href:a,s:(0,z.N)(""+e)},c));return(0,z.y)(d)},n7a=function(a,b,c){a=z.n("Tweet must be {$twitterMaxTweetLength} characters or less.",{twitterMaxTweetLength:z.A(c.j.fMa)});return(0,z.y)(""+a)},o7a=function(a){if(!a)return"";var b=[],c=z.nb(["grafId","noteId","command","startIndex","endIndex"]),d;for(d in a)b[c[d]]=a[d];return b.join("-")},p7a=function(a,b){return a instanceof z.hc?z.u(a.Vc(!0),b,void 0):z.u(z.wc(a),b,void 0)},P7=function(a){z.Lw.call(this);this.Cc=a.get("dom-model-converter");
this.yea={};this.pda={};this.W1={};this.qa=a;this.sl=a.get("request");this.na=a.get("route-builder");this.Aa=a.get("model-store");this.pb="";this.bfa=z.ml;this.bca=!1;this.Ih=null},Q7=function(a,b){var c=a.yea[b];c||(c=a.yea[b]=new z.JC,a.za("new_note_list",c,a));return c},q7a=function(a,b){if(!b)return!1;var c=b.Ia();if(a.content==c.substring(a.startIndex,a.endIndex))return!0;var d=new RegExp(z.taa(a.content),"gi"),c=(b=d.exec(c))&&d.exec(c);return b&&!c?(c=a.endIndex-a.startIndex,a.startIndex=b.index,
a.endIndex=b.index+c,a.content=b[0],!0):!1},R7=function(a,b,c){var d=b.Na(),e=b.Dg(),g=Q7(a,b.se()),k=g?g.indexOf(b):-1,l=b.Tu();b.yq(c);"HIDDEN"==c?a.Aa.remove(b):b=z.jC(a.Aa,b);var p=g?g.indexOf(b):-1;return{Il:a.sl.put(a.na.la(z.cDa,{postId:d,noteId:e}),{state:c}),EL:function(){b.yq(l);-1==p&&(-1==k?g.add(b):z.LC(g,b,k))}}},S7=function(a,b,c,d,e,g){var k=z.J(a.Tp(c,e),"replies"),l=z.Na(k,function(a){return a.ry()==b}),p=k[l];"HIDDEN"==g&&z.Sa(k,l);c=a.na.la(z.fDa,{postId:d,noteId:c,replyId:b});
a=a.sl.put(c,{state:g});var r=z.Na(k,function(a){return a.ry()==b});return{Il:a,EL:function(){-1==r&&z.Ya(k,l,0,p)}}},r7a=function(a,b,c){this.range=a;this.anchor=b;this.vC=b.getAttribute("name");this.highlight=c},T7=function(a,b){z.T.call(this);this.fb=a.get("screen-request");this.pBa=b;this.fZ=[];this.lw=null;this.Jn={};this.x2=!1;this.uga=null},U7=function(a,b,c){z.T.call(this);this.Oa=a.get("screen");this.ri=c;this.Va(b)},V7=function(a,b){z.T.call(this);this.Kb=a.get("dom-monitor");this.Ib=a.get("element-tracker");
this.Ga=a.get("popover");this.Oa=a.get("screen");this.hw=z.PB(a.get("activity-monitor"),1E4);this.Zt=a.get("placements-store");this.$a=b;this.vH=!1},s7a=function(a){var b=a.query(".js-postActionsFooter");return b?(a=z.HB(a.Ib),0>z.lw(b).top-a.height):!1},t7a=function(a){var b=a.query(".js-readNextMetabarRight");a.Zt&&b&&z.u(a.Zt.Yr(2),function(a){a&&z.P(b,z.qP,{items:a.items,context:2})})},W7=function(a,b,c,d){z.T.call(this);this.Oa=a.get("screen");this.sp=c;this.ri=d;this.bQ=!1;this.kw=this.RB=this.Uea=
null;this.Va(b)},u7a=function(a){return Math.floor((C6a(a)-a)/1E3)},X7=function(a,b,c){z.T.call(this);this.Oa=a.get("screen");this.m2=this.sp=null;this.va=b;this.$a=c;this.pa=a.get("request");this.na=a.get("route-builder")},w7a=function(a){if(v7a(a)){var b=a.na.la(z.Yza),c=a.va.id,d=Date.now(),e=z.J(z.Gl,"meterConfig").maxUnlockCount,g=z.nD.get("mpids")?z.nD.get("mpids").split(","):[];g&&-1==g.indexOf(c)&&g.length<e&&(g.push(c),z.nD.set("mpids",g.join(","),u7a(d),"/"));return a.pa.put(b,{postIds:g})}return z.wc({})},
v7a=function(a){var b=z.Rp();return a.va&&a.va.isSubscriptionLocked&&!z.Gk(b)&&a.va.creatorId!=b.userId&&!(a.va&&3==a.va.lockedPostSource&&!z.Sp())},Y7=function(a){z.T.call(this);this.Zt=a.get("placements-store")},x7a=function(a){a.Zt&&z.u(a.Zt.Yr(1),function(b){b&&z.P(a.oa(),z.qP,{items:b.items,context:9})})},Z7=function(a){z.T.call(this);this.Ib=a.get("element-tracker");this.DR=this.$t=null;this.$H=[];this.Dr=0;this.X3=y7a;this.h_=this.i_=null},$7=function(a){z.T.call(this);this.Zt=a.get("placements-store");
this.Ib=a.get("element-tracker");this.$t=null;this.$H=[];this.Dr=this.oR=null},z7a=function(a){a.Zt&&z.u(z.u(a.Zt.Yr(3),function(b){if(b)return z.P(a.oa(),z.qP,{items:b.items,context:44}),z.Nw(a,a.Ib,"refresh",a.Tga.bind(a)),a.Ib.Ym()}),a.Tga,a)},A7a=function(a){var b=z.CB(a.Ib,a.$t),c=z.YA(b)+b.Lf()/3,b=c7a(a.$t).map(function(b){return[b,z.CB(a.Ib,b)]}).filter(function(a){a=z.ha(a);var b=a.next().value;return z.YA(a.next().value)<c&&!z.Ds(z.yB(b))}),d=a.oR.fd();return(b=b.map(function(a){var b=z.ha(a);
a=b.next().value;var c=b.next().value,b=d.clone(),c=z.YA(c);a=z.xn(a).top||0;b.top=c+a;return b}).find(function(b){return!a.O0(b)}))?b.top:null},a8=function(a,b){z.T.call(this);this.qa=a;this.Ib=a.get("element-tracker");this.$a=b;this.i2=this.$a.pm;this.q2=this.dR=this.bR=null},b8=function(){},B7a=function(a){this.KQ=a},c8=function(a,b){return b?z.ks(a.KQ,b):null},C7a=function(a,b,c){d7a(a.KQ,function(a){var e=a.getAttribute("name");e&&b.call(c,a,e)})},D7a=function(a,b){return z.Tf(a.KQ,b)?a.KQ:null},
d8=function(a,b,c,d,e){z.PW.call(this,a,b);this.cb(new z.hW(c));this.cb(new z.cX(!1));this.cb(new z.fX(a));this.cb(new z.QW);this.cb(new z.iX(a,!1,!1));this.cb(new z.iU(d,!0));this.ml=!0;this.ym=d;this.sl=a.get("request");this.Ea=a.get("dialog");this.A1=e;this.ua()},E7a=function(){var a=z.n("Saving failed. You may be having connectivity issues or notes might be disabled on this post. Please try again.");return(0,z.y)(""+a)},F7a=function(){var a=z.n("Yikes! Something happened and we couldn’t dismiss this note.");
return(0,z.y)(""+a)},G7a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this note.");return(0,z.y)(""+a)},H7a=function(){var a=z.n("Yikes! Something happened and we couldn’t delete this reply.");return(0,z.y)(""+a)},I7a=function(){var a=z.n("The note has been dismissed.");return(0,z.y)(""+a)},J7a=function(){var a=z.n("The note has been deleted.");return(0,z.y)(""+a)},K7a=function(){var a=z.n("The reply has been deleted.");return(0,z.y)(""+a)},L7a=function(){var a=z.n("Write a note…");
return(0,z.y)(""+a)},M7a=function(){var a=z.n("Cancel");return(0,z.y)(""+a)},e8=function(a,b,c,d,e){d8.call(this,a,b,e||"Leave a note",400,d||null);this.pb=c;this.na=a.get("route-builder");this.yf=a.get("notes-data")},f8=function(a,b,c,d,e,g){d8.call(this,a,b,"Leave a reply…",200,d);this.na=a.get("route-builder");this.yf=a.get("notes-data");this.pb=c;this.Bfa=g||null;this.Re=e},O7a=function(a,b,c){var d='\x3cdiv class\x3d"quoteResponses js-quoteResponses"\x3e',e=a.quotes.length,g=a.responses.length||
a.f$;b=a.notes.length||a.wW;if(e||g||b){if(e){var e='\x3cdiv class\x3d"quoteResponses-section"\x3e'+z.A(z.Py({title:(0,z.N)(z.A(U6a())+" ("+z.A(a.quotes.length)+")"),Xf:!0},c)),k;k={Lla:a.quotes,CMa:!0};var l='\x3cdiv class\x3d"js-quotesList"\x3e';if(!k.CMa)var p=z.n("Learn more"),l=l+z.A(z.Py({title:(0,z.N)(""+z.A(U6a())),Xf:!0,Ug:(0,z.N)(""+z.A(z.Oy({href:(0,z.M)(""+z.H((0,z.yh)("https://medium.com/the-story/introducing-highlights-a4df69e8ed43"))),moreText:(0,z.N)(""+p),wb:!0},c)))},c));for(var p=
"list u-marginTop5 u-marginBottom15"+(k.Lla.length?"":" u-hide"),p=(0,z.N)(p),l=l+('\x3cul class\x3d"'+z.F(p)+'"\x3e'),p=k.Lla,r=p.length,t=0;t<r;t++){for(var w=p[t],B="",G=w.quotes,Q=G.length,R=0;R<Q;R++)B+=""+G[R].quoteId+(R!=Q-1?",":"");B=z.E(B);l+='\x3cli class\x3d"list-item list-item--inline u-border0" data-quote-ids\x3d"'+z.F(B)+'" data-quote-creator-id\x3d"'+z.F(w.user.userId)+'" data-action\x3d"highlight-quote" data-action-type\x3d"hover"\x3e'+z.A(z.Ak(z.D({user:w.user,He:!0},k),c))+"\x3c/li\x3e"}k=
(0,z.y)(l+"\x3c/ul\x3e\x3c/div\x3e");e=e+z.A(k)+"\x3c/div\x3e"}else e="";g?(g='\x3cdiv class\x3d"quoteResponses-section'+(a.f$?" is-withEditor":"")+'"\x3e'+z.A(z.Py({title:(0,z.N)(""+z.A(z.jk())),Xf:!0},c)),a.f$&&c.supportsEdit&&c.isAuthenticated?(k={},k=(0,z.y)('\x3cdiv class\x3d"js-inlineNewPostControl inlineNewPostControl inlineNewPostControl--quoteResponses"\x3e'+z.PO(z.D({user:c.currentUser,isCollapsed:!0,FD:!0,type:"quoteResponses",rv:(0,z.N)(""+z.A(z.Xfa()))},k),c)+"\x3c/div\x3e"),k=z.A(k)):
k="",g=g+k+N7a(a,0,c)+"\x3c/div\x3e"):g="";d+=e+g;if(a.dKa&&b){g=z.n("Who can see this?");d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed u-paddingLeft0 u-paddingRight0"\x3e';e=b="";k=a.post.homeCollection;k=a.post.creator.userId!=c.currentUser.userId?k?z.n("Private notes are visible to you, the author, and the editors of {$name}.",{name:z.A(k.name)}):z.n("Private notes are visible to you, the author, and the editors of any publication this story is added to."):k?z.n("Private notes are visible to you and the editors of {$name}.",
{name:z.A(k.name)}):z.n("Private notes are visible to you and the editors of any publication this story is added to.");e+=k;e=(0,z.y)(e);e=""+z.A(e);e=(0,z.N)(e);b+='\x3cspan data-tooltip\x3d"'+z.F(e)+'"\x3e'+g+"\x3c/span\x3e";g={};g=(0,z.y)(z.Ki(z.D({name:"lock",size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14 14.052a1 1 0 0 1-.992.998H5.992A.99.99 0 0 1 5 14.052v-4.004a1 1 0 0 1 .992-.998h7.016a.99.99 0 0 1 .992.998v4.004zM7 5.445C7 4.187 8.114 3.15 9.5 3.15c1.385 0 2.5 1.04 2.5 2.295V8.05H7V5.445zm6.008 2.605H13V5.445c0-1.822-1.578-3.295-3.5-3.295C7.577 2.15 6 3.618 6 5.445V8.05h-.008A2 2 0 0 0 4 10.048v4.004a1.99 1.99 0 0 0 1.992 1.998h7.016A2 2 0 0 0 15 14.052v-4.004a1.99 1.99 0 0 0-1.992-1.998z" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
g)));g=(0,z.N)(""+z.A(g));e=z.n("Private notes");e=(0,z.y)(""+e);b={ZLa:g,title:(0,z.N)(""+z.A(e)),Xf:!0,Ug:(0,z.N)(b),l:"heading--privateNotes"};b=(0,z.y)(z.My(z.D({Yi:(0,z.N)(""+z.Ny(b,c)),RIa:!0},b)));b=d+=z.A(b);d=""+('\x3cdiv class\x3d"privateNotes-list js-notesList'+(a.wW?" is-showingNoteEditor":"")+(0==a.notes.length?" is-empty":"")+'"\x3e');g=a.notes;e=g.length;for(k=0;k<e;k++)d+=g8({note:g[k],post:a.post,lM:a.lM},0,c);a.wW?(g=a.post.creator,a="",g=c.currentUser.userId==g.userId?z.n("Leave yourself a note"):
z.n("Send {$name} a private note…",{name:z.A(g.name)}),a+=g,a=(0,z.y)(a),a='\x3cdiv class\x3d"privateNotes-actions js-noteActions"\x3e'+z.A(z.vj({action:"show-note-editor",text:(0,z.N)(""+z.A(a)),l:"privateNotes-prompt"},0,c)),g=z.y,e='\x3cdiv class\x3d"privateNotes-editor"\x3e'+z.A(z.Bk({user:c.currentUser,Af:!0},c))+'\x3cdiv class\x3d"js-noteEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',k=z.n("Send"),k=(0,z.y)(""+k),c=g(e+z.A(z.vj({action:"save-note",isPrimary:!0,l:"js-saveNoteButton",
text:(0,z.N)(""+z.A(k))},0,c))+z.A(z.vj({action:"hide-note-editor",text:(0,z.N)(""+z.A(M7a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e"),c=a+c+"\x3c/div\x3e"):c="";c=(0,z.y)(d+("\x3c/div\x3e"+c));d=b+('\x3cdiv class\x3d"quoteResponses-inner privateNotes"\x3e'+c+"\x3c/div\x3e\x3c/div\x3e")}}else 0<a.zE&&(a=z.n("Show next tip"),b=z.n("Show previous tip"),d+='\x3cdiv class\x3d"quoteResponses-section quoteResponses-section--fullBleed quoteResponses-section--tips u-textAlignCenter u-paddingLeft0 u-paddingRight0"\x3e\x3cdiv class\x3d"quoteResponses-section--tipsInner u-alignMiddle"\x3e'+
z.A(z.wj({Fb:!0,Xc:!0,wa:!0,action:"previous-highlight-tip",icon:(0,z.N)(""+z.A(z.Vda())),title:(0,z.N)(""+b)},c))+"\x3cdiv class\x3d'u-alignBlock quoteResponses-section--tipsContent u-paddingLeft20 u-paddingRight20 js-highlightTip'\x3e\x3c/div\x3e"+z.A(z.wj({Fb:!0,Xc:!0,wa:!0,action:"next-highlight-tip",icon:(0,z.N)(""+z.A(z.Wda())),title:(0,z.N)(""+a)},c))+"\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");return(0,z.y)(d+"\x3c/div\x3e")},N7a=function(a,b,c){return(0,z.y)(z.A(z.uP({posts:a.responses,source:"quoteResponses",
DU:!0},0,c)))},g8=function(a,b,c){var d,e=null==a.note.replies?null:a.note.replies.length,g=null==a.note.replyId,k=a.post.creator.userId==c.currentUser.userId,l=a.post.creator.userId==a.note.author.userId;d=a.note.author.userId==c.currentUser.userId;b=k||(null==a.post.homeCollection?null:a.post.homeCollection.virtuals.permissions.canEditPosts);var p=""+(g?"js-note-item"+(a.note.noteId?" js-note-"+a.note.noteId:""):"js-reply-item"+(a.note.replyId?" js-reply-"+a.note.replyId:"")),p=z.E(p),p='\x3cdiv class\x3d"privateNotes-item '+
z.F(p)+' js-note" data-note-id\x3d"'+z.F(a.note.noteId)+'"\x3e'+(g?z.A(z.Ak({user:a.note.author},c)):z.A(z.NN({user:a.note.author},c)))+'\x3cdiv class\x3d"privateNotes-authorLockup"\x3e\x3cdiv class\x3d"privateNotes-author"\x3e'+z.A(z.Wj({user:a.note.author},c));g||!(k||d||(null==a.post.homeCollection?0:a.post.homeCollection.virtuals.permissions.canEditPosts))||l||a.nka?k="":(k=z.n("(Editor)"),k=(0,z.y)(""+k),k='\x3cspan class\x3d"privateNotes-author--supplemental"\x3e '+z.A(k)+"\x3c/span\x3e");p=
p+k+'\x3c/div\x3e\x3cdiv class\x3d"privateNotes-supplemental"\x3e'+z.A(z.Zg(Number(a.note.createdAt),c))+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"privateNotes-content js-privateNotesContent"\x3e';k=z.A(z.Kt(String(a.note.content),c));l=String(k).replace(/(\r\n|\r|\n)/g,"\x3cbr\x3e");k=z.dg(k,z.fg)?(0,z.y)(l,z.Eca(k)):l;d=""+(p+k+"\x3c/div\x3e"+(d?P7a({note:a.note,isPrimary:g},c):""));if(g){d+='\x3cdiv class\x3d"privateNotes-replies'+(e?"":" is-empty")+' js-repliesList"\x3e';if(e)for(e=a.note.replies,
g=e.length,p=0;p<g;p++)k=e[p],d+=g8({note:k,post:a.post,nka:a.note.author.userId==k.author.userId},0,c);e=d;a.lM?(g=z.y,d='\x3cdiv class\x3d"privateNotes-editor privateNotes-editor--reply"\x3e'+z.A(z.BP({user:c.currentUser,Af:!0},c))+'\x3cdiv class\x3d"js-replyEditor"\x3e\x3c/div\x3e\x3cdiv class\x3d"buttonSet"\x3e',p=z.n("Send"),p=(0,z.y)(""+p),g=g(d+z.A(z.vj({action:"save-reply",isPrimary:!0,text:(0,z.N)(""+z.A(p))},0,c))+z.A(z.vj({action:"hide-reply-editor",text:(0,z.N)(""+z.A(M7a()))},0,c))+"\x3c/div\x3e\x3c/div\x3e")):
g="";g="\x3c/div\x3e"+g+'\x3cdiv class\x3d"privateNotes-actions'+(b?" privateNotes-actions--withDismiss":"")+' u-clearfix"\x3e';a.lM?(d=z.y,p=z.n("Reply"),p=(0,z.y)(""+p),d='\x3cdiv class\x3d"u-floatLeft"\x3e'+d(z.A(z.vj({isPrimary:!0,action:"show-reply-editor",l:"privateNotes-prompt",text:(0,z.N)(""+z.A(p))},0,c)))+"\x3c/div\x3e"):d="";d=e+(g+d+(b?'\x3cdiv class\x3d"u-floatRight"\x3e'+P7a({note:a.note,isPrimary:!0,Vja:!0},c)+"\x3c/div\x3e":"")+"\x3c/div\x3e")}return(0,z.y)(d+"\x3c/div\x3e")},P7a=
function(a,b){var c=z.y,d=a.isPrimary?a.note.noteId:a.note.replyId,e=a.Vja?"dismiss-note":a.isPrimary?"delete-note":"delete-reply";a=a.Vja?z.n("Dismiss note"):z.n("Delete");a=(0,z.y)(""+a);a=z.A(a);return c(z.A(z.vj({actionValue:d,action:e,l:"privateNotes-delete js-deleteNote",text:(0,z.N)(""+a)},0,b)))},Q7a=function(a,b,c){b="";if(0==a.R9)a=1==a.zE?z.n("People highlighted this passage. You can click on an existing highlight to add to it, like below:"):z.n("{$topQuoteCount} people highlighted this passage. You can click on an existing highlight to add to it, like below:",
{topQuoteCount:z.A(a.zE)}),b+=a,b+='\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Ig(z.yi({imageId:"1*SyXCciYXeNpx4-GUAuh0XQ.gif"},0,c)))+'"\x3e';else if(1==a.R9)a=z.n("Or, select any passage to create your own highlight and tell the author and others what resonated with you:"),b+=a+'\x3cimg class\x3d"quoteResponses-tipAnimation" src\x3d"'+z.F(z.Ig(z.yi({imageId:"1*dEp02HXMKtAeKxsV5MWqGg.gif"},0,c)))+'"\x3e';else if(2==a.R9){a=z.n("so that you can save your highlights and share them with others.");
var d=z.n("Sign up and create a profile");b+=z.A(z.vj({text:(0,z.N)(""+d),ac:!0,source:(0,z.N)(""+z.A(z.Ch({name:c.j.oc.Goa,susiEntry:c.j.Ha.jF}))),l:"u-textUnderline"},0,c))+" "+a}return(0,z.y)(b)},h8=function(a,b,c,d,e,g,k,l){z.T.call(this);this.qa=a;this.xa=a.get("butter-bar");this.$a=b;this.Re=c;this.fk=e;this.ze=a.get("quotes-data");this.yf=a.get("notes-data");this.Dj=a.get("responses-data");this.nf=g;this.A1=d;this.F2=(this.xI=k)?k.fj():null;this.Of=this.Kc=null;this.hk={};this.Bda=!!z.Sp();
this.Cda=!!z.Up();this.sB=this.Bda&&this.Cda&&z.JE(b);this.cr=null;this.OP=0;this.Jga=H6a(this.ze,this.Re);this.Pw=l;this.Va(this.Tq());this.Cea=z.Sp()?2:3},R7a=function(a){a.ob(".js-block").forEach(function(a){this.Ta(a,"mouseenter",this.wva,this);this.Ta(a,"mouseleave",this.Y3,this)},a)},S7a=function(a){a.ob(".js-note").forEach(function(a){this.Ta(a,"mouseenter",this.uva,this);this.Ta(a,"mouseleave",this.Y3,this)},a)},T7a=function(a,b){var c=a.query(".js-note-"+b);a.hk[b]||(a.hk[b]=new f8(a.qa,
c.querySelector(".js-replyEditor"),a.$a.Na(),b,a.Re),z.Nw(a,a.hk[b],"saving",a.Qya,a),z.Nw(a,a.hk[b],"save",a.Lya,a),z.Nw(a,a.hk[b],"fail",a.Jxa,a));z.Ic(c,"is-noteEditorVisible");a.hk[b].focus()},U7a=function(a,b){var c=a.hk[b];c&&(c.ib()&&c.jd(""),a=a.query(".js-note-"+b),z.Mc(a,"is-noteEditorVisible"))},V7a=function(a,b,c){var d=c8(a.nf,a.Re);if(d){var e=[];a.Pw&&(e=a.Pw.quotes.map(function(a){return a.fj()}));(0,z.rb)(d.querySelectorAll(".markup--quote"),function(a){var d=a.getAttribute("data-creator-ids").split(" "),
d=z.Ra(d,b);if(this.Pw)var l=a.getAttribute("name").split(" "),d=d&&(0,z.sc)(l,z.Ra.bind(null,e));z.Oc(a,"is-selected",c&&d)},a)}},i8=function(a){return(a=z.hs(a,function(a){return z.Hc(a,"js-note-item")}))&&a.getAttribute("data-note-id")},W7a=function(a,b,c,d){b=new z.pE(b,300);b.Va(c);b.subscribe("dismiss",d,a);b.ua();return b},j8=function(a){var b=a.gc(),c=a.Fd();a=a.Ce();1<b.length&&(a=b[0].Ia().length);var d=new z.Tr;d.uq(b[0].getName());d.Jg(c);z.K(d,"endIndex",a);d.jd(b[0].Ia().substring(c,
a));return d},k8=function(a,b){b%=a.Cea;0>b&&(b=a.Cea-1);a.OP=b;(b=a.query(".js-highlightTip"))&&z.P(b,Q7a,{R9:a.OP,zE:a.Jga})},l8=function(a,b,c,d){z.T.call(this);this.Va(this.Tq(d));this.Kb=a.get("dom-monitor");this.$a=b;this.Hda=!b.Za().Wr()||b.Pb();this.pb=b.Na();this.nf=c;this.ze=a.get("quotes-data");this.Dj=a.get("responses-data");this.yf=a.get("notes-data");this.uw=null;this.Lh={}},X7a=function(a,b){b.forEach(function(a){a&&m8(this,a)},a)},m8=function(a,b){if(!a.uw)if(c8(a.nf,b)){var c=Y7a(a,
b),c=Z7a(a,c),c=$7a(a,c),c=a8a(a,c);a.Lh[b]=c;b8a(a,b)}else delete a.Lh[b]},c8a=function(a,b){if(!a.uw){var c=a.Lh[b];if(c){var d=c.length,c=$7a(a,c),c=a8a(a,c);a.Lh[b]=c;d!=c.length?b8a(a,b):c.forEach(function(a){a.Xa&&a.offsetTop&&(a.Xa.style.top=a.offsetTop+"px")})}}},d8a=function(a,b,c){return z.Pa(a.Lh[b]||[],function(a){return a.Xa==c})},Y7a=function(a,b){var c=[];Q7(a.yf,b).Xg(function(a){var e=a.cD(),g;e?(g=this.yf.aU(e),e=g.jb(),g=z.J(g,"endIndex")):(e=0,g=a.ib().length);c.push({anchor:b,
startIndex:e,endIndex:g,notes:[a],quotes:[],responses:[]})},a);if(a.Hda)return c;(a.ze.cu[b]||[]).forEach(function(a){var e=e8a(a);c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[a],responses:[]})},a);E7(a.Dj,b).forEach(function(a){var e=C7(a);e&&(e=D7(e)&&D7(e).lo())&&(e=e8a(e),c.push({anchor:b,startIndex:e.startIndex,endIndex:e.endIndex,notes:[],quotes:[],responses:[a]}))},a);return c},Z7a=function(a,b){var c=[];b.sort(function(a,b){return a.startIndex-b.startIndex});
b.forEach(function(a){var b=z.Na(c,function(b){return b.endIndex>=a.startIndex-1&&b.startIndex<=a.endIndex+1});0<=b?this.VH(c[b],a):c.push(a)},a);return c},a8a=function(a,b){var c=[];b.forEach(function(a){if(a.offsetTop){var b=z.Na(c,function(b){return 30>=Math.abs(b.offsetTop-a.offsetTop)});0<=b?this.VH(c[b],a):c.push(a)}},a);return c},b8a=function(a,b){a.ob(".js-paragraphControl-"+b).forEach(z.Mf);a.Lh[b]=a.Lh[b].map(function(a){var b=f8a(this,a),b=z.Ov(g8a,b);b.style.top=a.offsetTop+"px";a.Xa=
b;this.oa().appendChild(a.Xa);z.Ic(b,"is-visible");return a},a)},f8a=function(a,b){var c=b.notes,d=b.responses,e=y7(a.ze,b.quotes),g=d?d.length:0,k=c?c.length:0,l=0,p=0,r=0,t=!1,w=!1,B={},G={},Q=z.Rp().userId,R=a.$a.Za().Cf().mb();c.forEach(function(a){var b=a.aK();b&&((a=z.J(a,"replies"))&&a.forEach(function(a){k++;a.author&&(a.author.userId==Q&&l++,a.author.social&&a.author.social.isFollowing&&(B[a.author.userId]=a.author),G[a.author.userId]=!0)}),G[b.userId]=!0,b.userId==Q&&l++,b.userId==R?p++:
r++,b.social&&b.social.isFollowing&&(B[b.userId]=b))});e.forEach(function(a){a=a.user;G[a.userId]=!0;a.userId==Q&&(t=!0);a.social&&a.social.isFollowing&&(B[a.userId]=a)});d.forEach(function(a){a=a.Cf();G[a.userId]=!0;a.userId==Q&&(w=!0);a.social&&a.social.isFollowing&&(B[a.userId]=a)});c=b.quotes.filter(function(a){return"anon"==a.mb()});return{postId:a.pb,vC:b.anchor,bKa:k,TKa:g,dz:w,Vy:l,gla:p,cKa:r,d3a:e.length,cz:t,Jja:Object.keys(G).length,RHa:z.fb(B),zE:c.length}},e8a=function(a){var b=a.Fd(),
c=a.Ce();1<a.paragraphs.length&&(c=a.paragraphs[0].text.length);return{startIndex:b,endIndex:c}},$7a=function(a,b){var c=z.iw();return b.map(function(a){var b=this.nf.get(a.anchor),g=this.$a.dj(b);if(!g)return a;var k;4==g.type&&(g.Ia()&&(k=b.querySelector("figcaption")),k||(k=b));if(!k){g=a.startIndex+1;b=[b];k=0;for(var l=null;0<b.length&&k<g;)if(l=b.pop(),!(l.nodeName in z.FKa))if(3==l.nodeType){var p=l.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");k+=p.length}else if(l.nodeName in z.SQ)k+=
z.SQ[l.nodeName].length;else for(p=l.childNodes.length-1;0<=p;p--)b.push(l.childNodes[p]);k=l}g=z.lw(k,!0);a.offsetTop=Math.round(g.top+c.top);return a},a)},g8a=function(a,b,c){b=z.y;var d='\x3cdiv class\x3d"paragraphControls js-paragraphControl js-paragraphControl-'+z.F(a.vC)+' u-noUserSelect"\x3e',e=z.y,g;if(a.bKa||a.TKa){g='\x3cdiv class\x3d"notesMarker u-noUserSelect" data-action\x3d"select-anchor" data-action-value\x3d"'+z.F(a.vC)+'"\x3e';var k;k={};k=(0,z.y)(z.Ki(z.D({name:"asteriskFilled",
size:"19px",content:(0,z.N)('\x3csvg class\x3d"svgIcon-use" width\x3d"19" height\x3d"19" viewBox\x3d"0 0 19 19" \x3e\x3cpath d\x3d"M14.78 8.07a8.681 8.681 0 0 0-.427-1.383.478.478 0 0 0-.584-.27l-3.12.77V4.034c0-.247-.19-.48-.43-.5a7.23 7.23 0 0 0-1.38 0c-.24.02-.43.253-.43.5V7.19L5.3 6.415a.48.48 0 0 0-.583.27c-.18.448-.324.91-.426 1.383-.05.24.1.5.32.58l3.06.754-1.98 2.956c-.14.196-.13.502.04.67.34.332.7.632 1.09.896.2.136.49.077.63-.117l2.09-3.114 2.09 3.112c.15.193.43.252.63.116.39-.26.75-.56 1.09-.89.17-.17.19-.47.04-.67L11.4 9.41l3.06-.76a.517.517 0 0 0 .32-.58" fill-rule\x3d"evenodd"/\x3e\x3c/svg\x3e')},
k)));g=g+z.A(k)+"\x3c/div\x3e"}else g="";var l=k="",p="",r=1==a.Vy?z.n("a note"):z.n("notes"),p=p+(""+r),p=z.E(p);1==a.Jja&&(0<a.Vy||a.cz||a.dz)&&(0<a.Vy&&a.cz&&a.dz?(p=z.n("highlighted, responded, and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Vy&&a.dz?(p=z.n("responded and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):0<a.Vy&&a.cz?(p=z.n("highlighted and left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.cz&&a.dz?(p=z.n("highlighted and responded"),l+=" "+p):a.cz?
(p=z.n("highlighted"),l+=" "+p):0<a.Vy?(p=z.n("left {$noteCountText}",{noteCountText:""+p}),l+=" "+p):a.dz&&(p=z.n("responded"),l+=" "+p));l=z.E(l);k+='\x3cspan class\x3d"paragraphControls-itemText"\x3e';p="";if(0<a.gla&&0==a.cKa&&!a.cz&&!a.dz)c=1==a.gla?z.n("Note to self"):z.n("Notes to self"),p+=c;else{r="";if(0<a.zE)var t=z.n("Top highlight"),r=r+t;p+=z.A(z.eP(z.D({social:a.RHa,isActive:0<a.Vy||a.cz||a.dz,Ki:a.Jja,m7:!0,oKa:!0,hia:(0,z.N)(r)},a),c));p+=z.A(l)}p=(0,z.N)(p);k+=z.A(z.XIa(z.D({text:p},
a)))+"\x3c/span\x3e";a=(0,z.y)(k);a=e(g+a);return b(d+a+"\x3c/div\x3e")},n8=function(a,b,c){z.T.call(this);this.qa=a;this.Ja=a.get("app");this.cua=a.get("floating-components");this.Oa=a.get("screen");this.ub=a.get("screen-service");this.Kb=a.get("dom-monitor");this.$a=b;this.we=b.we;this.pm=this.we.querySelector(".js-postField");this.Vea=this.Oa.oa().querySelector(".js-notesPositionContainer");this.ze=a.get("quotes-data");this.yf=a.get("notes-data");this.yf.subscribe("new_note_list",this.gya,this);
this.Dj=a.get("responses-data");this.mm=null;this.nf=new B7a(this.we.querySelector(".js-notesSource"));this.RH=this.Lh=this.JR=null;this.Lh=new l8(a,b,this.nf,this.Vea);this.track(this.Lh);this.RH=this.Lh.oa();this.nm=this.a1=null;this.Ue=c},p8=function(a,b){if(a.isActive()){var c=(b=b||a.a1)&&b.uU,d=b&&b.noteId;c&&(a.qx(c),d&&a.yf.Tp(d,c)&&a.nm&&z.u(a.nm,function(){return o8(a,c,null,d)}));z.xoa(a.Ja,"")}else a.a1=b||null},o8=function(a,b,c,d,e,g){var k={Wl:!0,c7:z.Sv()};a.O2();c=new h8(a.qa,a.$a,
b,d||"",c||null,a.nf,e||null,g||null);c.subscribe("set-active-highlight",a.Rfa,a);c.subscribe("reset-highlight",a.xBa,a);c.subscribe("close",a.O2,a);b=g&&g.Xa?g.Xa:a.nf.get(b);g=z.Eya(a.cua);g.Rn=b;b=g.LE(c);b.lJ=k;k=b.fX(a.Mn.bind(a));k.uR=!0;a.mm=k.ua()},h8a=function(a,b,c){var d=a.$a.dj(c8(a.nf,b));if(d&&4!=d.type){z.Rs(d,4);if(c){if(!q7a(c,d))return;z.Ps(d,z.ys(c.startIndex,c.endIndex,c.id))}c=a.$a.Pb();var e=a.$a.Za();c={mode:c?"edit":"view",Rj:z.dt(e),media:null,am:null,sections:!0,Jk:!1,Gk:!1,
Fl:!1,Sf:!1,postId:e.id};a.nf.get(b).innerHTML=z.At(d,z.Gl,c)}},i8a=function(a,b){var c=z.$m();if(!c||c.isCollapsed())if(b&&(c=b),!c||c.isCollapsed())return null;b=c.Vf();var d=D7a(a.nf,b);if(!d)return null;a=(b=z.hs(b,z.qB,d))&&a.$a.dj(b);if(!b)return null;var d=z.nw(c,b,!0),e=z.nw(c,b,!1);return-1==d||-1==e?null:new r7a(c,b,new z.Tr({anchor:b.getAttribute("name"),startIndex:d,endIndex:e,content:a.Ia().substring(d,e)}))},j8a=function(){},q8=function(a,b){z.T.call(this);this.Qh=b||V6a;this.fb=a.get("screen-request");
this.va=null;this.i4=a.get("screen-view-state");this.qa=a;this.dga=this.m3=!1;this.U1=this.Kc=null},r8=function(a){z.Lw.call(this);this.Cz=a},k8a=function(a,b,c){a=z.na(a)?new z.td(a):a;(a=e7a(a,b,c||{}))&&(new r8(a)).focus()},l8a=function(a){this.pa=a.get("request");this.na=a.get("route-builder")},s8=function(a){z.Il.call(this);this.qa=a;this.wG=a.get("dialog");this.pa=a.get("request");this.na=a.get("route-builder");this.xa=a.get("butter-bar");this.sJ=this.Ea=this.Hx=this.va=null;this.TP=!1},n8a=
function(a){var b=a.Ea.query(".js-tweetEditor-image"),c=a.Ea.query(".js-tweetEditor-imageContainer"),d=a.Ea.query(".js-tweetEditor-imageStatus");z.Ic(c,"u-hide");var e=m8a(a);e.base64=!0;z.v(z.u(a.pa.post(z.Nv(h7a),e,{wC:!1,withCredentials:!1}),function(a){b.src="data:image/png;base64,"+a;z.Mc(c,"u-hide");z.Ic(d,"u-hide");this.TP=!0},a),function(a){z.Hw(a);z.P(d,j7a)},a)},o8a=function(a,b){return 280>=G7(b)?!0:(b=a.Ea.query(".js-tweetEditor-text"),(new z.qz(b,{name:"shimmy-shake",duration:400})).start(),
a=a.Ea.query(".js-tweetEditor-error"),z.P(a,n7a),!1)},m8a=function(a){var b=a.va,c=a.Hx.WLa;a=a.Hx.VLa;var d=b.creator,e=b.approvedHomeCollection,g=z.Gl,k=null;e&&(k=e.image);var l=null;e&&e.logo&&e.logo.imageId&&(l=e.logo.imageId);var p=null;e&&e.tintColor&&2==e.colorBehavior&&e.logo&&e.logo.imageId&&(p=e.tintColor);var r=null;e&&e.tintColor&&(r=z.wKa(e.tintColor),r=z.Fr(r,.6).color);return new H7({content:c,altText:a,title:b.title,author:d&&d.name,date:z.Yg(b.createdAt,g),authorAvatarId:d&&d.imageId,
collection:e&&e.name,collectionAvatarId:k?k.imageId:null,collectionLogoId:l,collectionBackgroundColor:p,collectionHighlightColor:r,version:2})},p8a=function(a){this.pa=a.get("request");this.na=a.get("route-builder");this.qa=a},q8a={hTa:1,jTa:2,iTa:3,kTa:4,lTa:5,gTa:6,$isProtoEnum:!0};z.q(v7,z.L);z.f=v7.prototype;z.f.ba=function(){return""};z.f.ca=function(){return""};z.f.Bv=z.h(314);z.f.Ed=z.h(440);z.f.Rb=z.h(444);z.f.ha=function(){return v7.prototype};
z.f.ea={name:"PlacementSlot",ia:!1,fields:{location:{name:"location",g:function(){return q8a},h:1},index:{name:"index",g:z.X,h:2}},ka:{}};z.f.Rb=z.Y(444,function(a){return z.K(this,"index",a)});z.f.Ed=z.Y(440,function(){return z.J(this,"index")});z.q(w7,z.L);z.f=w7.prototype;z.f.ba=function(){return""};z.f.ca=function(){return"Placement"};z.f.tf=function(){return z.J(this,"items")};z.f.Nc=z.h(394);z.f.Bv=z.h(313);z.f.Ed=z.h(439);z.f.Rb=z.h(443);z.f.ha=function(){return w7.prototype};
z.f.ea={name:"Placement",ia:!1,fields:{items:{name:"items",g:function(){return z.QL},ra:z.V,h:1},location:{name:"location",g:function(){return q8a},h:2},index:{name:"index",g:z.X,h:3}},ka:{}};z.f.Rb=z.Y(443,function(a){return z.K(this,"index",a)});z.f.Ed=z.Y(439,function(){return z.J(this,"index")});z.f.Nc=z.Y(394,function(a){return z.K(this,"items",a)});z.m(z7,z.Zd);z7.prototype.yk=function(a){var b={};z.jD(this,b,a.Ub(),"");return b};
z7.prototype.Jb=function(a,b){if(!a||!b)return null;var c=new a;Object.keys(b).forEach(function(a){for(var e=a.split(/[[\]]+/).filter(function(a){return!!a}),g=c,k=e.shift();k;){var l=z.sh(g,k);if(!l)break;var p=l.g();if(l.ra()){var r=z.oh(g,k)||[],t=e.shift(),w=Number(t);if(void 0===t||!Number.isInteger(w)||0>w)break;if(p.prototype instanceof z.fh)l=r[w],l||(l=new p,r[w]=l),z.K(g,k,r),g=l;else{if(void 0!==e.shift())break;p=x6a(b[a],l);r[w]=p;z.K(g,k,r)}}else if(p.prototype instanceof z.fh)r=z.oh(g,
k),r||(r=new p,z.K(g,k,r)),g=r;else{if(void 0!==e.shift())break;p=x6a(b[a],l);z.K(g,k,p)}k=e.shift()}});return c};z.q(A7,z.uh);z.f=A7.prototype;z.f.ba=function(){return""};z.f.ca=function(){return""};z.f.Yr=z.h(582);z.f.tW=z.h(435);z.f.ha=function(){return A7.prototype};z.f.ea={name:"PlacementsResponse",ia:!1,fields:{placements:{name:"placements",g:function(){return w7},ra:z.V,h:1},stateParams:{name:"stateParams",g:function(){return z.HM},h:2}},ka:{}};z.q(B7,z.L);z.f=B7.prototype;z.f.ba=function(){return""};
z.f.ca=function(){return""};z.f.tW=z.h(436);z.f.ha=function(){return B7.prototype};z.f.ea={name:"PlacementsRequestQuery",ia:!1,fields:{requestContext:{name:"requestContext",g:function(){return z.hq},h:1},slots:{name:"slots",g:function(){return v7},ra:z.V,h:2},stateParams:{name:"stateParams",g:function(){return z.HM},h:3}},ka:{}};z.PW.prototype.pW=z.Y(597,function(a){a!=this.dQ&&this.Ab&&(this.Ab.ji.contentEditable=a);this.dQ=a});z.QF.prototype.fX=z.Y(588,function(a){this.Mn=a;return this});
z.VF.prototype.fX=z.Y(587,function(a){this.Mn=a;return this});z.BF.prototype.f6=z.Y(586,function(a){a=C7(a);if(!a)return null;a=D7(a)&&D7(a).lo();return a?(a=a.gc())&&a.length?a[0].getName():null:null});A7.prototype.Yr=z.Y(582,function(){return z.J(this,"placements")});
z.kD.prototype.Yr=z.Y(581,function(a,b,c){var d=this;a=z6a(A6a(new B7,a),b);c&&a.tW(c);c=(new z7).yk(a);var e=this.na.la(z.Zza,{},c);return z.lD(this,e,function(){return z.u(d.pa.get(e,{background:!0}),function(a){a=d.Ka.kc(A7,a);d.Aa.rc(a);return a})})});z.fx.prototype.Tp=z.Y(498,function(){return z.J(this,"note")});z.eD.prototype.Tp=z.Y(497,function(a){return this.mc("Note",a)});z.Sr.prototype.ry=z.Y(471,function(){return z.J(this,"replyId")});
z.fx.prototype.ry=z.Y(470,function(){return z.J(this,"replyId")});z.Qr.prototype.kz=z.Y(469,function(a){return z.K(this,"highlight",a)});z.Qr.prototype.aU=z.Y(468,function(){return z.J(this,"highlight")});z.Qr.prototype.wv=z.Y(467,function(a){return z.K(this,"author",a)});z.Sr.prototype.wv=z.Y(466,function(a){return z.K(this,"author",a)});z.Qr.prototype.aK=z.Y(465,function(){return z.J(this,"author")});z.Sr.prototype.aK=z.Y(464,function(){return z.J(this,"author")});
z.Qr.prototype.cD=z.Y(463,function(){return z.J(this,"highlightId")});z.Qr.prototype.yq=z.Y(462,function(a){return z.K(this,"state",a)});z.Sr.prototype.yq=z.Y(461,function(a){return z.K(this,"state",a)});z.$w.prototype.yq=z.Y(460,function(a){return z.K(this,"state",a)});z.Qr.prototype.Dg=z.Y(459,function(){return z.J(this,"noteId")});z.Sr.prototype.Dg=z.Y(458,function(){return z.J(this,"noteId")});z.fx.prototype.Dg=z.Y(457,function(){return z.J(this,"noteId")});
z.kr.prototype.xv=z.Y(456,function(a){return z.K(this,"authorId",a)});z.Qr.prototype.xv=z.Y(455,function(a){return z.K(this,"authorId",a)});z.Sr.prototype.xv=z.Y(454,function(a){return z.K(this,"authorId",a)});B7.prototype.tW=z.Y(436,function(a){return z.K(this,"stateParams",a)});A7.prototype.tW=z.Y(435,function(a){return z.K(this,"stateParams",a)});z.Hp.prototype.hf=z.Y(356,function(){return z.J(this,"catalogId")});z.aK.prototype.hf=z.Y(355,function(){return z.J(this,"catalogId")});
z.SJ.prototype.hf=z.Y(354,function(){return z.J(this,"catalogId")});z.QL.prototype.hf=z.Y(353,function(){return z.J(this,"catalogId")});z.yJ.prototype.hf=z.Y(352,function(){return z.J(this,"catalogId")});z.vL.prototype.hf=z.Y(351,function(){return z.J(this,"catalogId")});z.pK.prototype.hf=z.Y(350,function(){return z.J(this,"catalogId")});z.nL.prototype.hf=z.Y(349,function(){return z.J(this,"catalogId")});z.mL.prototype.hf=z.Y(348,function(){return z.J(this,"catalogId")});
z.lL.prototype.hf=z.Y(347,function(){return z.J(this,"catalogId")});z.kr.prototype.hf=z.Y(346,function(){return z.J(this,"catalogId")});z.fx.prototype.hf=z.Y(345,function(){return z.J(this,"catalogId")});z.wG.prototype.hf=z.Y(344,function(){return z.J(this,"catalogId")});z.yp.prototype.Bv=z.Y(316,function(a){return z.K(this,"location",a)});z.cq.prototype.Bv=z.Y(315,function(a){return z.K(this,"location",a)});v7.prototype.Bv=z.Y(314,function(a){return z.K(this,"location",a)});
w7.prototype.Bv=z.Y(313,function(a){return z.K(this,"location",a)});z.Vn.prototype.kU=z.Y(73,function(){return z.J(this,"point")});var N6a=/(?:https?:\/\/|www\.)\w[\w~#-@![\]]*/g;F7.prototype.kU=function(){var a=window.document.body;return z.Tf(a,this.si.node)?this.si:this.Uk&&z.Tf(a,this.Uk)?z.CM(this.LQ,this.Uk):this.Re&&(a=z.ks(this.Zta,this.Re))?z.CM(this.LQ,a):null};z.q(H7,z.L);z.f=H7.prototype;z.f.ba=function(){return""};z.f.ca=function(){return""};z.f.ib=function(){return z.J(this,"content")};
z.f.jd=function(a){return z.K(this,"content",a)};z.f.Eb=function(){return z.J(this,"title")};z.f.Hc=function(a){return z.K(this,"title",a)};z.f.aK=function(){return z.J(this,"author")};z.f.wv=function(a){return z.K(this,"author",a)};z.f.getDate=function(){return z.J(this,"date")};z.f.setDate=function(a){return z.K(this,"date",a)};z.f.Lb=function(){return z.J(this,"collection")};z.f.setVersion=function(a){return z.K(this,"version",a)};z.f.hM=function(a){return z.K(this,"template",a)};
z.f.Qd=function(){return z.J(this,"subtitle")};z.f.vf=function(a){return z.K(this,"subtitle",a)};z.f.ha=function(){return H7.prototype};
z.f.ea={name:"TextshotInfo",ia:!1,fields:{content:{name:"content",g:z.W,h:1},altText:{name:"altText",g:z.W,h:2},title:{name:"title",g:z.W,h:3},author:{name:"author",g:z.W,h:4},date:{name:"date",g:z.W,h:5},authorAvatarId:{name:"authorAvatarId",g:z.W,h:6},collection:{name:"collection",g:z.W,h:7},collectionAvatarId:{name:"collectionAvatarId",g:z.W,h:8},collectionLogoId:{name:"collectionLogoId",g:z.W,h:9},collectionBackgroundColor:{name:"collectionBackgroundColor",g:z.W,h:10},collectionHighlightColor:{name:"collectionHighlightColor",
g:z.W,h:11},version:{name:"version",g:z.X,h:12},base64:{name:"base64",g:z.FG,h:13},template:{name:"template",g:z.W,h:14},mainStat:{name:"mainStat",g:z.W,h:15},mainStatTitle:{name:"mainStatTitle",g:z.W,h:16},subtitle:{name:"subtitle",g:z.W,h:17},icon:{name:"icon",g:z.W,h:18},imgKey:{name:"imgKey",g:z.W,h:19}},ka:{}};z.q(I7,z.Tl);I7.prototype.zL=function(){if(!this.lk)return null;var a=this.lk.kU();if(!a)return null;var b=this.um.kU();return b?z.tm(a.node,a.offset,b.node,b.offset):null};var r8a={pUa:"quote-respond"};
z.q(K7,z.T);z.f=K7.prototype;z.f.zk=function(){return this.zm.zk()};z.f.ma=function(){K7.ya.ma.call(this);z.Nw(this,this.S_,"data-redirect-type-quote",this.qxa,this);this.Ta(this.we,"click",this.Gw,this);z.KE(this.$a)&&z.Qv()&&this.Ta(this.we,"mouseover",this.Oua,this);this.$a.Za().Wr()&&!this.$a.Pb()&&z.v(this.ze.load(this.$a.Na()),z.Hw);var a=this.zk();a&&(z.Nw(this,a,"quote",this.Lua,this),z.Nw(this,a,"quote-respond",this.Mua,this),z.Nw(this,a,"show",this.a4,this),z.Nw(this,a,"hide",this.Kxa,this))};
z.f.qxa=function(a){var b=z.zE(this.zm,this.zk().Dx);b&&(a.url=new z.td(this.na.la(z.iDa,{postId:this.$a.Na()},{paragraphs:JSON.stringify([b.yy.Jb().Ub()]),startOffset:b.start,endOffset:b.end})))};z.f.Gw=function(a){z.hs(a.target,function(a){if(a===this.we)return!0;var c=z.zB(a);if(3==c)return!0;if(7==c){if(c=$6a(this,a))if(L7(this,c),z.Qv())N7(this,c);else{var d=new z.nE;Y6a(this,c,a,d)}return!0}return!1}.bind(this))};
z.f.Oua=function(a){z.hs(a.target,function(a){if(a===this.we)return!0;var c=z.zB(a);if(3==c)return!0;if(7==c){c=z.$m();if(!(c&&!c.isCollapsed()||this.zk()&&this.zk().jq())&&(c=$6a(this,a))){var d=this.we.querySelector('.markup--quote[name~\x3d"'+c.fj()+'"]');a=new z.pE(a,100);Y6a(this,c,d,a);L7(this,c)}return!0}return!1}.bind(this))};
z.f.a4=function(){var a=z.$m();a&&!a.isCollapsed()&&L7(this,null);if(z.KE(this.$a)&&(a=z.zE(this.zm,this.zk().Dx))){var a=z.ewa(this.ze,a.yy,a.start,a.end),b=this.zk().Sa().querySelector(".js-highlightMenuQuoteButton");z.Oc(b,"is-active",!!a)}};z.f.Kxa=function(){this.Fp&&L7(this,null)};
z.f.Lua=function(){if(z.KE(this.$a)){var a=z.uE(this.zk());if(a){var b=a.range,c=a.mJa,a=this.zk().Sa().querySelector(".js-highlightMenuQuoteButton"),d=z.Hc(a,"is-active"),b=z.zE(this.zm,b);z.v(z.u(this.ze.toggle(b.yy,b.start,b.end,!c),function(a){z.AKa();d?z.wE(this.zk()):N7(this,a);var b=c?"selection_menu":"quote_click_menu";O7(this,a.fj(),!d,b)},this),z.Hw)}}};
z.f.Mua=function(){if(z.KE(this.$a)&&z.Gl.supportsEdit){var a=z.uE(this.zk());if(a){var b=z.zE(this.zm,a.range);z.v(z.u(this.ze.create(b.yy,b.start,b.end,1,!0),function(a){O7(this,a.fj(),!0,"selection_menu_quote_respond");this.za("quote-respond",a,b.yy.name)},this),z.Hw)}}};
z.f.Vua=function(a){var b=this.Fp,c=M7(this,b),d=b.Fd(),e=b.Ce(),b=a.query(".js-quoteAttributions-pileOn"),g=z.Hc(b,"is-active");z.v(z.u(this.ze.toggle(c,d,e,!0),function(b){var l=a.query(".js-quoteAttributions-pileOn");z.Pc(l,"is-active");if(l=z.lE(this.ze,c,d,e)){var p=X6a(this,l),r=a.query(".js-quoteAttributions-info");z.P(r,M6a,p)}else a.Oc();!g&&z.Qv()&&(a.Oc(),N7(this,l));l=z.Qv()?"quote_hover":"quote_click_mobile";O7(this,b.fj(),!g,l)},this),z.Hw)};
z.f.Wua=function(){if(z.KE(this.$a)&&z.Gl.supportsEdit){var a=M7(this,this.Fp),b=this.Fp.Fd(),c=this.Fp.Ce();z.v(z.u(this.ze.create(a,b,c,1,!0),function(b){O7(this,b.fj(),!0,"quote_respond");this.za("quote-respond",b,a.name)},this),z.Hw)}};z.f.Xua=function(){var a=b7a(this,this.Fp);a&&z.twa(this.zm,a)};
z.f.Ffa=function(){var a=new I7(this.we),b=this.ze.cu,c=Object.keys(b).concat(this.eca);z.Za(c);c.forEach(function(a){var c=b[a]||[],g=this.$a;if(g=(a=g.we&&z.ks(g.we,a))&&this.$a.dj(a))K6a(g,c),a.innerHTML=z.At(g,z.Gl,z.zwa(this.$a)),z.Rya(this.AAa,a)},this);this.eca=Object.keys(b);(a=a.restore())&&a.select()};z.q(P7,z.Lw);z.f=P7.prototype;
z.f.load=function(a){if(!z.Sp())return z.wc([]);this.pb=a;this.Ih||(this.Ih=z.v(z.u(this.sl.get(this.na.la(z.aDa,{postId:a}),{background:!0}),this.yAa,this),z.Hw));return this.Ih.Vc()};z.f.cq=function(){return this.bca};z.f.ej=function(){return this.bfa};z.f.aU=function(a){return this.pda[a]||null};z.f.Tp=function(a,b){return z.mN(Q7(this,b),a)};z.f.kz=function(a,b){this.pda[a]=b};z.f.Na=function(){return this.pb};
z.f.yAa=function(a){var b=a.references.User;this.bfa=a.post.visibility;var c=a.value;if(c)for(var d=0;d<c.length;d++){var e=c[d];if("HIDDEN"!=e.state){var g=e.replies,k=b;if(g)for(var l=0;l<g.length;l++){var p=g[l],r=p.authorId||null;p.author=r&&k[r]||null}g=e.anchor;k=e.authorId||null;e.author=k&&b[k]||null;g=Q7(this,g);e=z.Rr(e);g.add(z.jC(this.Aa,e))}}if(a=a.highlights)for(b=0;b<a.length;b++)this.kz(a[b].id,z.Mn.Jb(z.Tr,a[b]));this.bca=!0};z.m(T7,z.T);T7.prototype.Yr=function(a){var b=this;if(this.x2){var c=new z.hc;(0,window.setTimeout)(function(){return c.callback()},s8a);return p7a(c,function(){return b.Yr(a)})}if(this.Jn[a])throw Error("Requesting multiple placements for the same location ("+a+") is not supported.");this.fZ.push((new v7).Bv(a).Rb(0));var d=new z.hc;this.Jn[a]=d;this.lw||(this.lw=(0,window.setTimeout)(this.xAa.bind(this),t8a));return d};
T7.prototype.xAa=function(){var a=this;this.x2=!0;z.qc(z.v(z.u(this.fb.Yr(this.pBa,this.fZ,this.uga),function(b){var c=b.placements;b=b.stateParams;if(!c)return z.fb(a.Jn).forEach(function(a){return a.callback(null)});c.forEach(function(b){a.Jn[b.location].callback(b)});a.uga=b}),function(b){z.fb(a.Jn).forEach(function(a){return a.Yg(b)})}),function(){var b=a.fZ;if(!z.la(b))for(var c=b.length-1;0<=c;c--)delete b[c];b.length=0;z.lb(a.Jn);(0,window.clearTimeout)(a.lw);a.lw=null;a.x2=!1})};
var s8a=20,t8a=500;z.m(U7,z.T);U7.prototype.ma=function(){z.T.prototype.ma.call(this);z.u(z.Pl(300),this.Yra,this)};
U7.prototype.Yra=function(){if(this.ri&&this.ri.postIds&&this.ri.postIds.length){for(var a=this.ob(".js-meterThumbnail"),b=new z.hc,c=0;c<this.ri.postIds.length;c++){var d=a[c],e=d.querySelector(".js-thumbnailImage"),g=z.Nv(z.yi,{imageId:this.ri.previewImageIds[c]?this.ri.previewImageIds[c]:"1*gqOHypRwp9HBuHaiSx6kWQ.png",strategy:"crop-fixed",width:40,height:40});z.mn(e,"background-image",'url("'+g+'"');z.u(b,this.YY.bind(this,d,c==a.length-1))}b.callback()}};
U7.prototype.YY=function(a,b){b=new z.qz(a,{name:b?"pulse-grow-50-110":"pulse-grow-50-105",duration:800+(b?200:0)});var c=z.u(new z.qz(a.querySelector(".js-thumbnailImage"),{name:"fade-in",duration:800}),function(){z.Ic(a,"is-read")}),d=new z.qz(a.querySelector(".js-thumbnailText"),{name:"color-light-to-white",duration:800});return new z.Hl([b.start(),c.start(),d.start()])};z.m(V7,z.T);V7.prototype.ma=function(){z.T.prototype.ma.call(this);var a=this.Oa.query(".js-postActionsBar");a&&(this.Va(a),(a=this.Oa.rx)?(z.Nw(this,a,"show",this.hC.bind(this,!0)),z.Nw(this,a,"dock",this.hC.bind(this,!0))):z.Nw(this,this.Kb,"scroll-up",this.hC.bind(this,!0)),z.Nw(this,this.Kb,"scroll-down",this.hC.bind(this,!1)),this.hC(!0),z.ns(this.Oa.query(".js-openInAppButton")),t7a(this),z.Pv()||this.Ta(this.Oa.oa(),"mousemove",z.Nl(200,this.jI,this)))};V7.prototype.Ca=function(){z.T.prototype.Ca.call(this)};
V7.prototype.jI=function(a){if(!this.vH){var b=z.HB(this.Ib);a.clientY>b.height-100&&this.hC(!0)}};V7.prototype.hC=function(a){if(this.$a.isPublished()&&!(this.vH===a||a&&s7a(this))&&(a||z.Sp()||s7a(this))){var b=this.Ga.$c(),c;b&&(c=b.se())&&z.bg(c,"js-postActionsBarContent")&&b.Oc();(this.vH=a)?this.za(u8a):this.za(v8a);z.Oc(this.oa(),"is-visible",this.vH)}};var u8a="show",v8a="hide";z.m(W7,z.T);z.f=W7.prototype;
z.f.ma=function(){var a=this;z.T.prototype.ma.call(this);this.sp&&(z.Nw(this,this.sp,u8a,function(){z.Ic(a.oa(),"is-abovePostActions");a.bQ=!0}),z.Nw(this,this.sp,v8a,function(){z.Mc(a.oa(),"is-abovePostActions");a.bQ=!1}));z.U(this.oa()).fa("dismiss-meter",this.tt,this).fa("expand-meter",this.Tta,this);var b=this.ri.postIds&&1<this.ri.postIds.length,c=z.Jp().isMobile&&!z.Jp().isTablet;if(b||c)this.kw=(0,window.setTimeout)(this.tt.bind(this),w8a);z.u(z.Pl(300),this.ZAa,this)};
z.f.Ca=function(){this.RB&&(this.RB.cancel(),this.RB=null);this.kw&&((0,window.clearTimeout)(this.kw),this.kw=null);z.T.prototype.Ca.call(this)};z.f.tt=function(){var a=this;this.RB=new z.qz(this.oa(),{name:this.bQ?z.Jp().isMobile?"pop-shift-down-35":"pop-shift-down-44":"pop-shift-down-0",duration:550,timing:"ease-in-out"});z.u(this.RB,function(){z.ms(a.oa());a.za(x8a)});this.RB.start()};
z.f.Tta=function(){var a=this.query(y8a),b=this.query(z8a),c=this.query(A8a);z.ms(a);z.Ic(b,"is-visible");this.kw&&((0,window.clearTimeout)(this.kw),this.kw=null);z.P(c,P6a);z.Mc(c,"u-xs-hide");z.kx(z.RGa,{unlockCount:this.ri.postIds.length})};
z.f.ZAa=function(){var a=this;this.Oa.oa().appendChild(this.oa());this.Uea=new z.qz(this.oa(),{name:this.bQ?z.Jp().isMobile?"pop-shift-up-35":"pop-shift-up-44":"pop-shift-up-0",duration:800,timing:"ease-in-out"});z.u(this.Uea.start(),function(){if(a.ri&&a.ri.postIds&&a.ri.postIds.length){for(var b=a.ob(".js-meterThumbnail"),c=new z.hc,d=0;d<a.ri.postIds.length;d++)z.u(c,a.YY.bind(a,b[d],d==b.length-1));c.callback()}})};
z.f.YY=function(a,b){b=new z.qz(a,{name:b?"pulse-grow-50-110":"pulse-grow-50-105",duration:800+(b?200:0)});var c=z.u(new z.qz(a.querySelector(".js-thumbnailImage"),{name:"fade-in",duration:800}),function(){z.Ic(a,"is-read")}),d=new z.qz(a.querySelector(".js-thumbnailText"),{name:"color-light-to-white",duration:800});return new z.Hl([b.start(),c.start(),d.start()])};var w8a=6E3,A8a=".js-dismissMeterIndicator",y8a=".js-expandMeterButton",z8a=".js-moreInfo",x8a="dismissed";z.m(X7,z.T);X7.prototype.ma=function(){var a=this;z.T.prototype.ma.call(this);return z.u(z.v(w7a(this),z.Hw),function(b){b=b.meteringInfo;var c=a.Oa.Da();a.sp=new V7(c,a.$a);if(b&&0<=b.postIds.indexOf(a.va.id)){var d=z.Ov(W6a,{post:a.va,meteringInfo:b});a.m2=new W7(c,d,a.sp,b);a.Oa.track(a.m2);z.Nw(a,a.m2,x8a,function(){!z.Sp()&&z.Gl.useragent.isMobile&&(J6a(a.Oa,a.sp)||a.Oa.track(a.sp))})}else(d=a.Oa.query(".js-paywall"))&&a.Oa.track(new U7(c,d,b));if(!v7a(a)||z.Sp())J6a(a.Oa,a.sp)||a.Oa.track(a.sp)})};z.m(Y7,z.T);Y7.prototype.ma=function(){z.T.prototype.ma.call(this);x7a(this)};z.m(Z7,z.T);z.f=Z7.prototype;z.f.ma=function(){z.T.prototype.ma.call(this);this.$H=this.Q_();this.DR=z.CB(this.Ib,this.oa(),"fixed");z.Nw(this,this.Ib,"refresh",this.Y9.bind(this));var a=this.oa();z.Jc(a,["u-fixed","u-transition--fadeOut300"]);z.mn(a,"transform","translateY("+this.X3+"px)");this.vJ();this.Y9()};z.f.j9=function(a){this.$t=a;return this};z.f.Y9=function(){this.f1();this.j1()};
z.f.f1=function(){this.vJ();var a=this.DR.fd(),a=a.top+a.height;if(z.HB(this.Ib).top+this.X3<=this.i_)return this.W3();if(a>=this.h_)return this.bB()};z.f.j1=function(){var a=this.DR.fd(),b=z.HB(this.Ib);return b.height<B8a||this.Dr>b.top||this.O0(a)?this.g0():this.bS()};z.f.O0=function(a){return(0,z.sc)(this.$H,function(b){return z.GN(a,b.fd())})};z.f.bS=function(){z.QR(this.oa(),"u-transition--fadeOut300","u-transition--fadeIn300")};z.f.g0=function(){z.QR(this.oa(),"u-transition--fadeIn300","u-transition--fadeOut300")};
z.f.bB=function(){var a=this.oa();z.QR(a,"u-fixed","u-absolute");z.mn(a,"transform","translateY("+this.i_+"px)")};z.f.W3=function(){var a=this.oa();z.QR(a,"u-absolute","u-fixed");z.mn(a,"transform","translateY("+this.X3+"px)")};z.f.vJ=function(){var a=z.CB(this.Ib,this.$t);this.h_=z.YA(a)+a.Lf();this.i_=this.h_-this.DR.Lf()};z.f.Q_=function(){var a=this;return z.fR(this.$t).map(function(b){return z.CB(a.Ib,b)})};var y7a=150,B8a=400;z.m($7,z.T);z.f=$7.prototype;z.f.ma=function(){z.T.prototype.ma.call(this);this.oR=z.CB(this.Ib,this.oa());this.$H=this.Q_();z7a(this)};z.f.j9=function(a){this.$t=a;return this};z.f.Tga=function(){if(0==this.oR.Lf())this.za(t8,!1,0,0);else{var a=this.oa(),b=A7a(this);this.Dr!=b&&((this.Dr=b)?(z.mn(this.oa(),"transform","translateY("+b+"px)"),a&&z.Mc(a,"u-invisible")):a&&z.Ic(a,"u-invisible"),this.za(t8,!z.Hc(a,"u-invisible"),b||0,this.oR.Lf()))}};
z.f.O0=function(a){return this.$H.some(function(b){return z.GN(a,b.fd())})};z.f.Q_=function(){var a=this;return z.fR(this.$t).map(function(b){return z.CB(a.Ib,b)})};var t8="positioned";z.m(a8,z.T);a8.prototype.ma=function(){z.T.prototype.ma.call(this);this.bR=z.CB(this.Ib,this.i2);if(this.$a.isPublished()&&this.bR.Lf()>C8a){var a=z.Mw(this,".js-postShareWidget"),a=(new Z7(this.qa)).Va(a).j9(this.i2);a.Dr=z.YA(this.bR);this.dR=a;this.track(this.dR);z.Gl.variants.enable_related_reads_discovery&&(a=z.Mw(this,".js-sidebarRecirc"),this.q2=(new $7(this.qa)).Va(a).j9(this.i2),z.Nw(this,this.q2,t8,this.EEa.bind(this)),this.track(this.q2))}};
a8.prototype.EEa=function(a,b,c){this.dR.Dr=a?b+c:z.YA(this.bR);this.dR.Y9()};var C8a=300;b8.prototype.pT=function(a,b,c){return new K7(a,b,c)};b8.prototype.as=function(){return r8a};B7a.prototype.get=function(a){return c8(this,a)};z.q(d8,z.PW);z.f=d8.prototype;z.f.UI=!1;z.f.oB="";z.f.WI=0;z.f.qs=z.V;z.f.Dg=function(){return this.A1};z.f.save=function(){this.ib().length<=this.ym&&this.vl()};z.f.Gb=function(){(0,window.clearTimeout)(this.WI);d8.ya.Gb.call(this)};
z.f.ma=function(){function a(a){a.stopPropagation()}d8.ya.ma.call(this);this.oB=this.ib();this.jd(this.oB);this.Rx(13,this.E1,this);this.Rx(27,this.F1,this);this.Ab.Ta("blur",this.D1,!1,this);var b=this.Ab.Sa();z.aw(b,"keydown",a);z.aw(b,"keyup",a);z.aw(b,"keypress",a)};z.f.r8=function(a){return a};
z.f.vl=function(){if(this.isEnabled()){var a=this.ib().trim();if(a){this.pW(!1);var b=this.Wia(),a=this.Via(a);this.za("saving",a);z.nc(z.v(z.u(this.sl.post(b,a.Ub()),this.kya,this),this.iya.bind(this,a)),this.pW.bind(this,!0))}}};z.f.kya=function(a){this.za("save",this.r8(a.value))};z.f.iya=function(a,b){this.za("fail",a);this.Ea.error(E7a());z.Hw(b)};z.f.E1=function(a){if(this.Gr&&z.rX(this.Gr))return!1;a.shiftKey||(a.preventDefault(),this.save());return!0};
z.f.F1=function(a){if(this.Gr&&z.rX(this.Gr))return!1;a.preventDefault();this.jd(this.oB);this.za("cancel");return!1};z.f.D1=function(){this.UI&&(this.ib().length>=this.ym?(0,window.confirm)(this.$ia())?(this.jd(this.oB),this.za("cancel")):this.focus():this.WI=(0,window.setTimeout)(this.vl.bind(this),100))};z.q(e8,d8);z.f=e8.prototype;z.f.VY=null;z.f.wba=null;z.f.WY=null;z.f.fk=null;z.f.m0=null;z.f.l0=null;z.f.oda=null;z.f.kz=function(a){this.fk=a;this.m0=a.startIndex;this.l0=a.endIndex;this.oda=a.content;return this};z.f.$ia=function(){var a=z.n("Your note is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};z.f.r8=function(a){var b=z.Lv();a=z.Rr(a).wv(b).xv(b.mb());this.fk&&a.cD()&&this.yf.kz(a.cD(),this.fk);var b=this.yf,c;c=z.jC(b.Aa,a);Q7(b,c.se()).add(c);return a};
z.f.Wia=function(){return this.Dg()?this.na.la(z.bDa,{postId:this.pb,noteId:this.Dg()}):this.na.la(z.$Ca,{postId:this.pb})};z.f.Via=function(a){var b=z.Lv();a=(new z.Qr({content:a,anchor:this.VY,anchorContent:this.wba,anchorImage:this.WY?this.WY.Ub():null,replies:[],createdAt:Date.now()})).wv(b);null!=this.m0&&null!=this.l0&&(b=new z.Tr({anchor:this.VY,startIndex:this.m0,endIndex:this.l0,content:this.oda}),a.kz(b));return a};z.q(f8,d8);f8.prototype.$ia=function(){var a=z.n("Your reply is too long; do you want to abandon your changes?");return(0,z.y)(""+a)};f8.prototype.r8=function(a){var b=z.Lv();a=z.Kja(a).wv(b).xv(b.mb());z.J(this.yf.Tp(a.Dg(),this.Re),"replies").push(a);return a};f8.prototype.Wia=function(){return this.Bfa?this.na.la(z.eDa,{postId:this.pb,noteId:this.Dg(),replyId:this.Bfa}):this.na.la(z.dDa,{postId:this.pb,noteId:this.Dg()})};
f8.prototype.Via=function(a){var b=z.Lv();return(new z.Sr({replyId:"",postId:this.pb,noteId:this.Dg(),content:a,createdAt:Date.now()})).wv(b)};z.q(h8,z.T);z.f=h8.prototype;
z.f.ma=function(){h8.ya.ma.call(this);z.U(this.oa()).fa("show-note-editor",this.s3,this).fa("hide-note-editor",this.i0.bind(this,!0)).fa("show-reply-editor",this.hDa,this).fa("hide-reply-editor",this.sva,this).fa("save-note",this.RBa,this).fa("save-reply",this.SBa,this).fa("highlight-quote",this.vva,this).fa("dismiss-note",this.ica.bind(this,!0),this).fa("delete-note",this.ica.bind(this,!1),this).fa("delete-reply",this.hta,this).fa("previous-highlight-tip",this.vAa,this).fa("next-highlight-tip",this.Twa,
this);S7a(this);this.Dj&&x7(this.Dj)&&(R7a(this),z.Nw(this,x7(this.Dj),"add",this.hya,this));if(this.F2&&this.Bda&&this.Cda){var a=this.query(".js-inlineNewPostControl"),b=this.F2,c=this.$a.Na(),d=new z.LS(this.qa);d.YL("web-inline-quote-responses");d.Va(a);d.yG=!0;d.c_=!0;d.$Z=!0;d.hM(O6a);d.nB=b;d.cM(c);z.MS(d,!0);this.Kc=d;this.Kc.ua();a=j8(this.xI);this.za("set-active-highlight",this.Re,a)}this.fk&&(this.s3(),this.Of&&this.Of.focus());k8(this,0)};
z.f.Ca=function(){this.cr&&this.cr.s5();(this.fk||this.xI)&&this.za("reset-highlight",this.Re,null);h8.ya.Ca.call(this)};z.f.Gb=function(){z.rx(this.oa());z.Mf(this.oa());z.Kl(this.Kc);z.Kl(this.Of);z.Kl(this.cr);z.Ll(z.fb(this.hk));this.cr=this.hk=this.Of=this.Kc=null;h8.ya.Gb.call(this)};z.f.qo=function(){if(this.Of&&this.Of.ib())return!0;for(var a=z.fb(this.hk),b=0;b<a.length;b++)if(a[b]&&a[b].ib())return!0;return this.Kc&&!this.Kc.isDismissable()?!0:!1};
z.f.Tq=function(){var a=[],b=[],c=[],d=this.sB&&(this.fk||this.xI);d||(this.Pw?(a=this.ze?y7(this.ze,this.Pw.quotes):[],b=this.Pw.notes,c=this.Pw.responses):(b=this.yf?z.OC(Q7(this.yf,this.Re)):[],this.A1||(this.ze?(a=this.ze,a=y7(a,a.cu[this.Re]||[])):a=[],c=this.Dj?E7(this.Dj,this.Re):[])));return z.Ov(O7a,{post:this.$a.Za(),quotes:a,notes:b,responses:c,f$:!!this.F2,wW:d,lM:this.sB,zE:this.Jga,dKa:z.JE(this.$a)})};
z.f.hya=function(){var a=this.query(".js-postList"),b=z.Ov(N7a,{responses:E7(this.Dj,this.Re)});z.Nf(b,a);R7a(this)};
z.f.s3=function(){if(this.sB){if(!this.Of){var a=this.query(".js-noteEditor"),b=z.Nv(L7a),a=this.Of=new e8(this.qa,a,this.$a.Na(),null,b),b=this.Re,c=this.$a.dj(this.nf.get(this.Re)),d=c.Ia(),c=4==c.type?c.De():null;a.VY=b;a.wba=d;a.WY=c;(a=this.fk)&&this.Of.kz(a);z.Nw(this,this.Of,"saving",this.Pya,this);z.Nw(this,this.Of,"fail",this.Ixa,this);z.Nw(this,this.Of,"save",this.Kya,this)}z.Ic(this.query(".js-noteActions"),"is-noteEditorVisible");this.Of&&this.Of.focus()}};
z.f.RBa=function(){this.Of&&this.Of.save()};z.f.Pya=function(a){this.Of.jd("");var b=this.query(".js-notesList");a={note:a,post:this.$a.Za(),wW:this.sB,lM:this.sB};a=z.Ov(g8,a);b.appendChild(a);z.Mc(b,"is-empty");S7a(this);this.i0()};z.f.Kya=function(a){var b=this.query(".js-notesList").lastChild;a=a.Dg();z.Ic(b,"js-note-"+a);b.setAttribute("data-note-id",a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.Ixa=function(){var a=this.query(".js-notesList");a.removeChild(a.lastChild);z.Ic(a,"is-empty");this.s3()};z.f.i0=function(a){a?this.za("close"):this.Of&&(this.Of.ib()&&this.Of.jd(""),z.Mc(this.query(".js-noteActions"),"is-noteEditorVisible"))};z.f.hDa=function(a){(a=i8(a.target))&&this.sB&&T7a(this,a)};z.f.SBa=function(a){a=i8(a.target);(a=this.hk[a])&&a.save()};
z.f.Qya=function(a){var b=a.Dg();this.hk[b]&&this.hk[b].jd("");var c=this.yf.Tp(b,this.Re).author.userId==a.author.userId,d=this.query(".js-note-"+a.Dg()+" .js-repliesList");a={note:a,post:this.$a.Za(),nka:c};a=z.Ov(g8,a);d.appendChild(a);z.Mc(d,"is-empty");U7a(this,b)};z.f.Lya=function(a){var b=this.query(".js-note-"+a.Dg()).querySelector(".js-repliesList").lastChild;a=a.ry();z.Ic(b,"js-reply-"+a);(b=b.querySelector(".js-deleteNote"))&&b.setAttribute("data-action-value",a)};
z.f.Jxa=function(a){var b=this.query(".js-note-"+a.Dg()+" .js-repliesList");b.removeChild(b.lastChild);z.Ic(b,"is-empty");T7a(this,a.Dg())};z.f.sva=function(a){(a=i8(a.target))&&U7a(this,a)};z.f.vva=function(a){a=a.target;var b=a.getAttribute("data-quote-creator-id"),c=c8(this.nf,this.Re);c&&(this.cr&&this.cr.s5(),this.cr=W7a(this,c,a,function(){V7a(this,b,!1);z.Kl(this.cr);this.cr=null}),V7a(this,b,!0))};
z.f.uva=function(a){var b=c8(this.nf,this.Re);(a=this.yf.Tp(a.target.getAttribute("data-note-id"),this.Re))&&b&&(b=(b=a.cD())?this.yf.aU(b):null,this.za("set-active-highlight",this.Re,b))};z.f.wva=function(a){var b=c8(this.nf,this.Re),c;c=this.Dj;a=a.target.getAttribute("data-post-id");c=x7(c)?z.mN(x7(c),a):null;b&&c&&(b=C7(c))&&(b=D7(b)&&D7(b).lo())&&(c=b.gc())&&c.length&&(b=j8(b),this.za("set-active-highlight",this.Re,b))};
z.f.Y3=function(){var a=null;this.xI&&(a=j8(this.xI));this.fk&&(a=this.fk);this.za("reset-highlight",this.Re,a)};
z.f.ica=function(a,b){b=b.value;var c=this.yf.Tp(b,this.Re),d=this.query(".js-note-"+b);if(c&&d){z.ms(d);this.Y3();this.ob(".js-note-item").every(function(a){return z.Hc(a,"u-hide")})&&this.i0(!0);var e=R7(this.yf,c,"HIDDEN");z.v(e.Il,function(b){this.xa.ua(a?F7a():G7a(),"error");e.EL();z.ns(d);(400>b.status||499<b.status)&&R7(this.yf,c,"NEW")},this);z.u(this.xa.ua(a?I7a():J7a(),{type:"success",CE:!0}),function(){this.xa.Oc();e.EL();R7(this.yf,c,"NEW");z.ns(d)},this)}};
z.f.hta=function(a){var b=a.value,c=this.query(".js-reply-"+b),d=i8(a.target);if(d&&c){z.ms(c);var e=S7(this.yf,b,d,this.$a.Na(),this.Re,"HIDDEN");z.v(e.Il,function(){this.xa.ua(H7a(),"error");e.EL();z.ns(c);S7(this.yf,b,d,this.$a.Na(),this.Re,"")},this);z.u(this.xa.ua(K7a(),{type:"success",CE:!0}),function(){this.xa.Oc();e.EL();S7(this.yf,b,d,this.$a.Na(),this.Re,"");z.ns(c)},this)}};z.f.vAa=function(){k8(this,this.OP-1)};z.f.Twa=function(){k8(this,this.OP+1)};z.q(l8,z.T);z.f=l8.prototype;z.f.ma=function(){l8.ya.ma.call(this);var a=[];z.JE(this.$a)&&a.push(this.yf.load(this.pb));this.Hda||(a.push(this.ze.load(this.pb)),a.push(this.Dj.load(this.pb)));this.uw=z.u(z.u(z.u(z.zR(a),function(){this.uw=null},this),this.render,this),this.dsa,this);z.Nw(this,this.Kb,"resize-end",this.Zf,this)};z.f.Ca=function(){this.uw&&this.uw.cancel();l8.ya.Ca.call(this)};z.f.Gb=function(){this.uw=null;l8.ya.Gb.call(this)};
z.f.render=function(){C7a(this.nf,function(a,b){m8(this,b)},this)};z.f.Zf=function(){C7a(this.nf,function(a,b){c8a(this,b)},this)};z.f.dsa=function(){var a=this.ze.tp;z.Nw(this,a,"add",this.Kea,this);z.Nw(this,a,"remove",this.Kea,this);(a=x7(this.Dj))&&z.Nw(this,a,"add",this.Hya,this)};z.f.Kea=function(a){X7a(this,Object.keys(z.iwa(this.ze,a instanceof Array?a:[a])))};z.f.Hya=function(a){X7a(this,(a instanceof Array?a:[a]).map(this.Dj.f6,this.Dj))};
z.f.Tq=function(a){var b=window.document.createElement("div");b.className="notesMarkers";a.appendChild(b);return b};z.f.VH=function(a,b){z.pb(a,{startIndex:Math.min(a.startIndex,b.startIndex),endIndex:Math.max(a.endIndex,b.endIndex),notes:a.notes.concat(b.notes),quotes:a.quotes.concat(b.quotes),responses:a.responses.concat(b.responses)})};z.q(n8,z.T);z.f=n8.prototype;
z.f.ma=function(){n8.ya.ma.call(this);this.Ta(this.Oa.oa(),"click",this.wwa,this,!0);z.U(this.RH).fa("select-anchor",this.Wya,this);var a=this.$a.Za();if(a.Wr()&&!this.$a.Pb()){var b=z.Ap(a),b=2==a.visibility&&b&&!z.J(b.Pj(),"memberOfMembershipPlanId");a.allowResponses&&!b&&z.v(this.Dj.load(this.$a.Na(),"best"),z.Hw);z.v(this.ze.load(this.$a.Na()),z.Hw)}a.Pj().$J()&&(this.JQ=z.u(this.yf.load(this.$a.Na()),this.lya,this));this.a1&&p8(this,null);z.Nw(this,this.ub,"historyUpdate",function(){p8(this,
z.AE())},this);this.Ue&&z.Nw(this,this.Ue,"highlight",this.jya,this)};z.f.Gb=function(){z.Kl(this.Lh);this.Lh=null;z.Kl(this.mm);this.mm=null;this.RH&&z.U(this.RH).clear("select-anchor");this.JQ&&this.JQ.cancel();this.JQ=null;n8.ya.Gb.call(this)};z.f.kKa=function(a,b){o8(this,b,null,null,a)};z.f.lMa=function(){this.Lh&&this.Lh.Zf()};z.f.qo=function(){if(!this.mm)return!1;var a=this.mm.ib();return a?a.qo():!1};z.f.gya=function(a){a.subscribe("add",this.Sga,this);a.subscribe("remove",this.Sga,this)};
z.f.Sga=function(a){(z.la(a)?a:[a]).forEach(function(a){m8(this.Lh,a.se())},this)};z.f.lya=function(){var a=(0,z.Ea)();this.JQ=null;p8(this,z.AE());this.Ta(this.pm,z.aI,this.Q1,this);z.ey(z.tFa,(0,z.Ea)()-a)};z.f.Q1=function(a){(a=a.target.getAttribute("name"))&&c8(this.nf,a)&&c8a(this.Lh,a)};z.f.jya=function(){if(this.Ue){var a=i8a(this,this.Ue.Dx);z.wE(this.Ue);a&&(a=a.highlight,this.Rfa(a.anchor,a),o8(this,a.anchor,a))}};
z.f.wwa=function(a){if(this.mm){var b=a.target;if(!z.Tf(this.mm.oa(),b)){var c=this.mm.ib(),d;if(!(d=!c)){a:if(c.Of&&c.Of.ib())c=!0;else{d=z.fb(c.hk);for(var e=0;e<d.length;e++)if(d[e]&&d[e].ib()){c=!0;break a}c=c.Kc&&!c.Kc.hj()?!0:!1}d=!c}d&&(c=this.mm&&this.mm.Rn,d="select-anchor"==b.getAttribute("data-action"),this.O2(),c&&d&&z.Tf(c,b)&&a.stopPropagation())}}};
z.f.Mn=function(a){if(!z.Sv()){var b=a.Rn,c=z.lw(b);a.Nl();a=a.oa();var d=z.lw(a),e=window.innerHeight,g=window.innerWidth,k=this.Oa.query(".js-metabar"),l=0;k&&(l=z.lw(k).height);d.height>=e-l?f7a(a):(z.hw(b),b=c.top+d.height>=e?z.iw().top+e-d.height-10:z.hw(b),c=z.lw(this.RH).left+10,c+d.width>=g&&(c=g-d.width-10),a.style.top=b+"px",a.style.left=c+"px")}};z.f.O2=function(){z.Kl(this.mm);this.mm=null};
z.f.Wya=function(a){var b=z.hs(a.target,function(a){return z.Hc(a,"js-paragraphControl")},this.Vea),b=d8a(this.Lh,a.value,b);o8(this,a.value,null,null,null,b)};z.f.Rfa=function(a,b){if(this.$a.Pb()){var c=z.$m();this.JR=(c=c&&D7a(this.nf,c.Vf()))&&new I7(c)}h8a(this,a,b)};z.f.xBa=function(a,b){h8a(this,a,b);this.$a.Pb()&&this.JR&&(a=this.JR.restore())&&a.select();this.JR=null};
z.f.qx=function(a){if(this.nf&&(a=c8(this.nf,a))){a=Math.max(z.hw(a),0);var b=window.document.body;this.nm&&this.nm.cancel();this.nm=new z.Hn(b,"scrollTop",600,a)}};j8a.prototype.pT=function(a,b,c){return new n8(a,b,c)};z.m(q8,z.T);z.f=q8.prototype;z.f.qc=function(a){this.va=a};z.f.hM=function(a){this.Qh=a};z.f.pLa=function(a){this.m3=a};z.f.qLa=function(a){this.dga=a};
z.f.ma=function(){this.oa()?(z.T.prototype.ma.call(this),z.U(this.oa()).fa("show-responses-stream-editor",this.hza,this).fa("show-other-responses",this.jga,this),z.P(this.oa(),this.Qh,{post:this.va}),this.va.Wr()&&z.v(z.u(z.u(z.u(I6a(this.fb,this.va.Bb(),"best"),this.zfa.bind(this,"best")),this.eBa,this),function(){this.i4.A9&&this.jga()},this),z.Hw)):z.Hw("Attempted to initialize ResponsesStreamControl without root element.")};z.f.Ca=function(){z.U(this.oa()).clear("show-other-responses");z.T.prototype.Ca.call(this)};
z.f.zfa=function(a,b){this.isActive()&&(b=b.Pe,"best"==a?(a=this.query(".js-responsesStream"),z.Nw(this,b,"add",this.kea.bind(this,b)),this.kea(b)):a=this.query(".js-responsesStreamOther"),b&&(z.Up()||0<b.Me())&&a&&(z.P(a,z.qP,{items:z.OC(b),context:2}),b=new z.oS(this.qa,b),b.Va(a),b.Bd(2),this.track(b),z.ns(this.query(".js-responsesStreamWrapper"))),this.dga&&(a=z.hw(a),z.ew(window.document.body,0,a)))};
z.f.eBa=function(){var a=this.query(".js-inlineNewPostControl"),b=this.query(".js-responsesLoggedOutPrompt");z.Up()?a?(this.Kc=z.MS(B6a((new z.LS(this.qa)).YL("web-inline-post-response").cM(this.va.Bb()),z.Mv(z.Eh,{post:this.va,hW:!0})),this.m3).Va(a),this.track(this.Kc)):b&&this.m3&&(a=z.gw(b),b=z.hw(b),z.ew(a,0,b)):b&&z.Ic(b,"u-hide")};
z.f.jga=function(){this.U1||(this.U1=z.nc(z.u(z.u(I6a(this.fb,this.va.Bb(),"other"),this.zfa.bind(this,"other")),function(){z.ms(this.query(".js-showOtherResponses"));this.i4.A9=!0},this),function(){this.U1=null},this))};z.f.kea=function(a){(a=a.kl)&&a.next&&"other"==a.next.filter&&!this.i4.A9&&(z.ns(this.query(".js-responsesStreamWrapper")),z.ns(this.query(".js-showOtherResponses")))};z.f.fy=function(){this.Kc&&(z.lR(this.Kc.oa(),new z.fn(60,0,200,0)),this.Kc.fy())};
z.f.hza=function(){var a=this.query(".js-responsesStreamEditor"),b=this.query(".js-showResponsesStreamEditorButton");z.os(a)&&(z.ns(a),z.ms(b),this.fy())};z.q(r8,z.Lw);r8.prototype.focus=function(){this.isActive&&this.Cz.focus()};r8.prototype.close=function(){this.Cz&&!this.Cz.closed&&this.Cz.close();this.za("close");this.hg()};r8.prototype.isActive=function(){return this.Cz?!this.Cz.closed:!1};r8.prototype.Wa=function(){this.Cz=null;r8.ya.Wa.call(this)};z.f=l8a.prototype;z.f.oE=function(a,b,c){var d;d=z.Gl;var e=new z.Dh(z.Fl(d)),e=new z.td(e.Dl(a));d=J7(e,d);this.Yw(d);z.kx(z.LI,{postId:a.id,type:b,source:c,dest:"facebook",dialogType:"native"})};z.f.t9=function(a){var b;b=z.Gl;var c=new z.Dh(z.Fl(b));a=new z.td(c.la(z.Bu,{catalogSlug:a.hf(),username:a.Cf().Dk()}));b=J7(a,b);this.Yw(b)};z.f.u9=function(a){var b;b=z.Gl;var c=new z.Dh(z.Fl(b));a=new z.td(c.la(z.su,{sequenceSlug:a.td()}));b=J7(a,b);this.Yw(b)};
z.f.a6=function(){var a=this.na.la(z.HCa);return this.pa.get(a)};z.f.Yw=function(a){k8a(a,"facebook-share",{width:550,height:320})};z.q(s8,z.Il);
s8.prototype.open=function(a,b){this.va=a;this.Hx=b;this.Ea=this.wG.open({bodyHtml:z.Mv(k7a,this.Hx),type:"tweet"},!0);a=this.Ea.query(".js-tweetEditor-text");b=this.qa;var c=String,d;d=z.n("Enter tweet text.");d=(0,z.y)(""+d);this.sJ=new z.NX(b,a,c(d),!0);a=new z.iU(280,!0);a.Xba=G7;this.sJ.cb(a);a=S6a(g7a,this.Hx,z.Gl);this.sJ.jd(a);this.sJ.focus();n8a(this);z.U(this.Ea.cc).fa("remove-textshot",this.Wfa.bind(this,!1),this).fa("add-textshot",this.Wfa.bind(this,!0),this).fa("toggle-expand-image",this.aEa,
this);this.Ea.subscribe(z.Fy,this.NEa.bind(this))};s8.prototype.NEa=function(){var a=this.sJ.ib();if(o8a(this,a)){var b=this.TP?m8a(this):null;z.v(z.u(this.pa.post(this.na.la(z.FCa),{tweet:a,textshotInfo:b}),function(a){a=z.Nv(i7a,{id:a.value});a=z.Mv(m7a,{eMa:a});this.xa.ua(a,{type:"success",Pk:1E4})},this),function(a){z.Hw(a);this.xa.ua(l7a(),"error")},this);z.Zx(z.iFa,{postId:this.va.id,type:this.Hx.shareType,source:this.Hx.tLa,dest:"twitter",style:this.TP?"textshot":null});this.Ea.close()}};
s8.prototype.Wfa=function(a){this.TP=a;z.Oc(this.Ea.query(".js-tweetEditor-imageContainer"),"u-hide",!a);z.Oc(this.Ea.query(".js-tweetEditor-addTextshot"),"u-hide",a)};s8.prototype.aEa=function(){var a=this.Ea.query(".js-tweetEditor-image");z.Pc(a,"tweetEditor-image--expanded")};z.f=p8a.prototype;z.f.sLa=function(a,b){var c=z.Rp(),d=a.creator||{},e=E6a(b),g=D6a(b),k=T6a(a,z.Gl);(b=o7a(b.c6()))&&z.Bd(k,b||"");var l={name:d.name||"",username:d.username||"",twitterScreenName:d.twitterScreenName||"",url:k.toString(),content:a.title,user:c,WLa:e,VLa:g,shareType:"highlight",tLa:"highlight_menu"};z.v(z.u(this.qa.load("tweet-dialog"),function(b){b.open(a,l)}),z.Hw);z.Zx(z.LI,{postId:a.id,type:"highlight",source:"highlight_menu",dest:"twitter",dialogType:"inapp"});return!0};
z.f.oE=function(a,b,c,d,e){var g=z.Rp().userId,k="highlight"==c?g7a:z.Qja,l=z.Gl,p=a.creator||{};b={content:b,name:p.name||"",username:p.username||"",twitterScreenName:p.twitterScreenName||"",Bha:p.userId==g,url:T6a(a,l).toString(),collaborators:d||[]};d=d&&d.length?String(k(b,null,l)):S6a(k,b,l);k=new z.td("https://twitter.com/intent/tweet");z.Jd(k,"text",d);this.Yw(k);z.kx(z.LI,{postId:a.id,type:c,source:e,dest:"twitter",dialogType:"native"})};
z.f.t9=function(a){var b=z.Gl,c=new z.Dh(z.Fl(b)),c=(new z.td(c.la(z.Bu,{catalogSlug:a.hf(),username:a.Cf().Dk()}))).toString();a=z.C(""+z.ik(String(a.name))+((null==a.creator?null:a.creator.userId)!=b.currentUser.userId?" — "+z.Zr({twitterScreenName:null==a.creator?null:a.creator.twitterScreenName,name:null==a.creator?null:a.creator.name}):"")+" "+(""+c));b=new z.td("https://twitter.com/intent/tweet");z.Jd(b,"text",a);this.Yw(b)};
z.f.u9=function(a){var b=new z.Dh(z.Fl(z.Gl)),b=(new z.td(b.la(z.su,{sequenceSlug:a.td()}))).toString();a=z.C(""+z.ik(String(a.title))+" "+(""+b));b=new z.td("https://twitter.com/intent/tweet");z.Jd(b,"text",a);this.Yw(b)};z.f.Yw=function(a){k8a(a,"twitter-share",{width:670,height:420})};var D8a=z.Hx,E8a=D8a.Da();z.Kx(z.Kx(z.Kx(z.Kx(z.Kx(E8a.scope("screen").add("quotes",b8).add("quote-responses",j8a).add("responses-stream-control",q8).add("notes-data",P7),"PlacementsStore",T7),"Meter",X7),"PostMeterBar",W7),"PostFooterReadNext",Y7),"PostSidebar",a8);E8a.scope("app").add("twitter",p8a).add("facebook",l8a).add("tweet-dialog",s8);z.nN(D8a,"notes");}).call(this, _mdm);
